ejeschke/ginga

.travis.yml
scripts/ginga

Fix ginga seg fault

---

ginga/qtw/plugins/Contents.py

Fix race condition in Contents (Qt)

---

ginga/util/dp.py
ginga/util/wcs.py

Fixed a bug where user prefix is not propagated to image name in mosaic, and fixed a WCS warning. Also some auto whitespace removal by my Emacs.

Prefix bug fix in dp.py

---

ginga/misc/plugins/Cuts.py

--Do Not Merge-- Cuts fixes

---

ginga/misc/plugins/Cuts.py

Added an edit mode checkbox for Cuts

Editing support for Cuts

---

ginga/misc/plugins/MultiDim.py

A few fixes for MultiDim -
1) Fixes the activation problem of the slider
2) Fixes incorrect number of HDUs shown
3) Loads MultiDim if file opened has NAXIS >= 3
4) Fixes Slice display issue

--Do Not Merge-- MultiDim fixes

---

ginga/base/PlotBase.py
ginga/gtkw/Widgets.py
ginga/misc/plugins/Cuts.py
ginga/misc/plugins/MultiDim.py
ginga/qtw/QtHelp.py
ginga/qtw/Widgets.py
ginga/util/videosink.py

Added save support to-
1) Cuts - Save plot and data
2) MultiDim - Save support for images and movies(uses mencoder; still has some issues)

Save support

---

ginga/gtkw/Widgets.py
ginga/qtw/Widgets.py
ginga/util/videosink.py

Add file extension if omitted

---

ginga/misc/plugins/Cuts.py

A legend for the cuts plot using matplotlib.

Added Cuts legend

---

ginga/misc/plugins/Preferences.py

Change print functions to logger info. This is a follow-up to a fix in #155.

Replace print in Preferences

---

ginga/main.py
ginga/misc/plugins/LineProfile.py

Adds support for spectral analysis.
@ejeschke Is there a way to access MultiDim for the current header and data from this plugin?

Line Profile plugin

---

ginga/util/dp.py

Generalized version of the one submitted by @stscieisenhamer in #165. To be used for #162.

Add masktorgb() function

---

ginga/canvas/types/basic.py
ginga/gtkw/Widgets.py
ginga/misc/plugins/Cuts.py
ginga/qtw/Widgets.py

Slit support

---

ginga/examples/configs/plugin_Header.cfg
ginga/gtkw/plugins/Header.py
ginga/misc/plugins/HeaderBase.py
ginga/qtw/plugins/Header.py

Added preference to toggle header sort on load. This is based on a request in #189. c/c @hcferguson
@ejeschke, I don't have GTK but theoretically it should work on both Qt and GTK. Can you please double check? Thanks!

Added preference to toggle header sort on load

---

doc/manual/concepts.rst

Just a few minor tweaks to clarify or provide cross links.

minor tweaks to Core Concepts section of documentation

---

ginga/gtkw/Widgets.py
ginga/qtw/Widgets.py

Commented print statements in `Widgets.py` modules.

Commented print statements in Widgets

---

ginga/examples/configs/channel_Image.cfg
ginga/examples/configs/general.cfg

This addresses #171.
* Added channel config file example.
* Minor verbiage change in general config to be consistent with the new example.
@ejeschke, my organization of the config file is mainly educated guesses, so please double check. I also added notes below on the entries that I am really not sure about.

Added channel_Image.cfg example

---

.travis.yml

This PR opts in from the legacy to the container based travis.

Opting in container based travis

---

ginga/gw/GingaGw.py

Fix for #233.

---

doc/api/imageview.rst
doc/api/index.rst
ginga/ImageView.py
ginga/RGBMap.py

Added full API doc for `ImageView`, as part of #228. Also see #182.
I am not sure when I have time to do the rest, such that the cross-references work. So, we can just merge this first, and I'll open new PRs as able.

Added full API doc for ImageView

---

ginga/Control.py
ginga/examples/configs/plugin_Thumbs.cfg
ginga/misc/plugins/Thumbs.py

~~Qt~~ solution for `Thumbs` for #186.
~~If we want to be even more flexible, we can make the font color configurable, but will that be overkill?~~
Also see #190

Highlight active image in Thumbs (Qt)

---

ginga/examples/configs/plugin_Cuts.cfg
ginga/misc/plugins/Cuts.py

Fixed `Cuts` plot keep shrinking with legend enabled. Fixed "Save" and "Delete All" buttons not toggling on/off properly. Fixed "Save" logic. PEP8 stuff.
This fixes #131.

Fix Cuts plugin

---

ginga/misc/plugins/LineProfile.py

Mainly disables controls for 2D images

Line profile fixes

---

ginga/examples/configs/plugin_FBrowser.cfg
ginga/misc/plugins/FBrowser.py

`FBrowser` to auto resize column widths (regardless). This fixes #274.
Also see: #268, #263

FBrowser auto resizing column widths

---

ginga/examples/configs/plugin_Header.cfg
ginga/misc/plugins/Header.py

Enable automatic column resizing for `Header` global plugin, as requested by @ejeschke in #276.

Enable auto col resize for Header

---

ginga/gtkw/GtkHelp.py
ginga/qtw/QtHelp.py

Added directory browser widget (GTK and Qt). I need this for spacetelescope/stginga#87 but it is just generally useful for Ginga to have anyway.
Disclaimer: Untested under GTK but theoretically should work if http://stackoverflow.com/questions/10868167/make-filechooserdialog-allow-user-to-select-a-folder-directory answer is correct.

Added directory browser widget

---

ginga/misc/plugins/Pick.py

Enable changing label name in `Pick` subclass. Does not affect existing functionality.
Related issue: spacetelescope/stginga#97

Flexible Pick label text

---

ginga/tests/test_cmap.py
ginga/tests/test_imap.py

Added tests for the cmap and imap files

Tests for cmap and imap files

---

doc/manual/plugins_local/mosaic.rst
ginga/misc/plugins/Mosaic.py

Added documentation for Mosaic plugin. This is motivated by the fact that I have a subclass of Mosaic in `stginga` and I wish to cross-ref to this one.

Added doc for Mosaic plugin

---

ginga/Control.py
ginga/ImageView.py
ginga/canvas/CanvasMixin.py
ginga/canvas/CanvasObject.py
ginga/canvas/CompoundMixin.py
ginga/canvas/DrawingMixin.py
ginga/canvas/coordmap.py
ginga/canvas/types/astro.py
ginga/canvas/types/basic.py
ginga/canvas/types/image.py
ginga/canvas/types/layer.py
ginga/canvas/types/mixins.py
ginga/canvas/types/utils.py
ginga/examples/gw/example2.py
ginga/examples/gw/shared_canvas.py
ginga/examples/qt/example2_qt.py
ginga/gtkw/Widgets.py
ginga/misc/Bunch.py
ginga/misc/plugins/Drawing.py
ginga/qtw/CanvasRenderQt.py
ginga/qtw/Widgets.py
ginga/trcalc.py
ginga/web/pgw/Widgets.py
setup.cfg

This PR contains a number of small fixes for python 3, Qt 5.  It also cleans up and improves the support for plotting based on WCS coordinates. Additionally new rotate and scale edit control points are provided in the editing gui for shapes.  Some fixes for shared canvases are also included.

Rotate scale improvements

---

doc/manual/plugins.rst
doc/manual/plugins_global/colormappicker.rst

Saw some Sphinx warnings when I built the doc manually and fixed them.

Fix Sphinx warnings

---

ginga/qtw/ImageViewQt.py

The debug message was trying to format None as a float.
Made formatting generic.

Quick fix for scroll crash

---

ginga/AstroImage.py
ginga/BaseImage.py
ginga/Control.py
ginga/main.py
ginga/misc/plugins/Toolbar.py
ginga/table/AstroTable.py
ginga/util/io_fits.py

This is the same as PR #390, but includes extra fixes

io_fits refactoring + fixes

---

ginga/AstroImage.py
ginga/misc/plugins/MultiDim.py

Fixes #399 . Also see #397. Also some PEP8 clean-ups on `MultiDim` and `AstroImage`.

MultiDim to use new FITS I/O interface

---

experimental/plugins/Imexam.py

Minor updates to the original plugin to coincide with updates in the imexam module for prints and logging.
This should work with the current master and the release of 0.6.3 coming up

updated imexam plugin to work with imexam logging

---

ginga/rv/Control.py
ginga/rv/main.py

@ejeschke , the actual change is the last commit. The rest is just clean-up.
This adds support to the following command lines:
`ginga *.fits[1]`
`ginga *.fits[SCI,1]`
`ginga --sep *.fits[1]`
`ginga --sep *.fits[SCI,1]`
`ginga u*_c0m.fits[4] s*sci.fits`
EDIT: Does not really address #311. Sorry for the confusion.

Enable filepath with wildcard and extension from command line

---

ginga/rv/plugins/Histogram.py

Corrected Histogram docstring so its Help formats properly.

Correct Histogram docstring formatting

---

ginga/gw/Desktop.py

Fix #450 , as suggested by @ejeschke 
Also general PEP8 clean-up for `Desktop.py`

Allow movable tabs

---

ginga/util/io_fits.py

This was buried in #455 but is actually a standalone fix, so I put it in a new PR.

Fix inherit_primary_header setting being ignored

---

doc/install.rst

Fixed typo in install.rst

---

doc/optimizing.rst

Added openCV python wrapper link

---

doc/install.rst

* Added reference tag to the top
* Added a couple clarifying links (probably unnecessary)
* Fixed one link that I broke (whoops!)
* Restructured some lists to make the steps clearer

Reformatting, clarification, add reference tag

---

doc/manual/introduction.rst

In Ginga Viewer and Toolkit Manual section, simple edits, paragraph breaks.

In Ginga Viewer and Toolkit Manual section, simple edits, paragraph breaks

---

doc/manual/concepts.rst
doc/manual/index.rst

1) Changed the dangling footnote on workspace into a note in workspace section
2) Editorial fixes, paragraph breaks, list item capitalization fixes
3) Horizontal lines between sections

Editorial fixes, paragraph breaks, removal of dangling footnote

---

doc/manual/operation.rst

Multiple edits to enhance readability, in specific:
1) Added a note on "RV" specific documentation 
2) Formatted "RV" into ``RV`` to call attention
3) Converted textual sentences to list items for Color distribution algorithm and Intensity maps section
4) Changed section title "Terminology" to "Keyboard and mouse operations"

In General Operation sections, several edits for readability

---

doc/manual/plugins_local/pick.rst
ginga/rv/plugins/Pick.py

Fix #479 
p.s. The "comment" is only saved out as FITS header keyword but not as a comment line in ASCII. See astropy/astropy#6079

Pick save table auto-detect extension

---

ginga/qtw/Widgets.py
ginga/table/AstroTable.py

Follow-up of 797e508ac . Supersede #489. Fix #476.
Also follow-up of #461.

Fix error in Savedialog with filter, AstroTable naxispath

---

ginga/rv/plugins/Catalogs.py
ginga/util/catalog.py

Fix up `Catalog` behavior. Add user preference. PEP8 clean-ups.
Supersede #485.

Fix Catalog plugin GUI

---

setup.py

Separate PR for this as requested in https://github.com/ejeschke/ginga/pull/484#discussion_r117358189

Bump Astropy version to 1.x as 0.3 is pretty old

---

ginga/util/io_fits.py

Astropy v2.0 compatibility for MultiDim

---

ginga/Bindings.py
ginga/ImageView.py
ginga/aggw/CanvasRenderAgg.py
ginga/cairow/CanvasRenderCairo.py
ginga/canvas/CanvasObject.py
ginga/canvas/CompoundMixin.py
ginga/canvas/DrawingMixin.py
ginga/canvas/transform.py
ginga/canvas/types/astro.py
ginga/canvas/types/basic.py
ginga/canvas/types/image.py
ginga/canvas/types/mixins.py
ginga/cvw/CanvasRenderCv.py
ginga/examples/gl/example2_qt.py
ginga/examples/gl/example_wireframe.py
ginga/examples/matplotlib/example2_mpl.py
ginga/mockw/CanvasRenderMock.py
ginga/mplw/CanvasRenderMpl.py
ginga/opengl/CanvasRenderGL.py
ginga/opengl/ImageViewQtGL.py
ginga/pilw/CanvasRenderPil.py
ginga/qtw/CanvasRenderQt.py
ginga/rv/plugins/Catalogs.py
ginga/trcalc.py
ginga/web/bokehw/CanvasRenderBokeh.py

Refactors shapes to have a more unified representation of points. 
This allows more efficient sharing of code that operates of points, removes "2D-isms" for a more unified approach to coordinate points in the API, and makes internal canvas code more consistent between shapes.
Objects with (x, y) and (x1, y1, x2, y2) attributes are refactored to store the points in an array of points notation similar to polygon-based shapes.  Properties are provided for backward-compatible access to these attributes.

Refactor internal shapes code for point handling consistency

---

ginga/web/pgw/Viewers.py

Contender for smallest pull request of 2017?

Make use of default parameters for super call in Viewer.py

---

ginga/BaseImage.py

Fix numpy typo

---

.gitignore
README.rst
index.html

As a follow-up of https://github.com/ejeschke/ginga/issues/526#issuecomment-314899566

Update GitHub page

---

setup.py

As stated in https://github.com/ejeschke/ginga/pull/537#issuecomment-319181568

Bump min numpy to 1.9

---

ginga/gtk3w/Widgets.py
ginga/gtkw/Widgets.py
ginga/qtw/Widgets.py
ginga/web/pgw/Widgets.py

Add option to de-select a TreeView item

---

.travis.yml
appveyor.yml
ginga/misc/tests/test_Callback.py
ginga/misc/tests/test_Future.py
ginga/misc/tests/test_Task.py
ginga/tests/test_ImageView.py
ginga/tests/test_cmap.py
ginga/tests/test_colordist.py
ginga/tests/test_colors.py
ginga/tests/test_imap.py
ginga/tests/test_wcs.py
setup.cfg

Fix #317 
Fix #554 
Close #346 
TODO:

Update CI test matrix, tests cleanup, add ColorDist tests

---

ginga/examples/gw/example2.py
ginga/examples/gw/widgets.py
ginga/examples/pg/example2_pg.py
ginga/web/pgw/ImageViewPg.py
ginga/web/pgw/PgHelp.py
ginga/web/pgw/Plot.py
ginga/web/pgw/Viewers.py
ginga/web/pgw/Widgets.py
ginga/web/pgw/js/ginga_pg.css
ginga/web/pgw/js/ginga_pg.js

This provides a number of enhancements to the web "pg" widgets backend
- support for many more widgets, using jquery and optional jqxwidgets
- improvements for VBox/HBox and much better packing/alignment
No significant API changes and backward compatible.

Enhanced pg widgets

---

ginga/examples/configs/general.cfg

Add save_layout to general.cfg example

---

.travis.yml
ginga/rv/plugins/Catalogs.py
ginga/rv/plugins/Compose.py
ginga/util/addons.py
setup.cfg

Add E741 to white-list to fix PEP8 test

---

ginga/examples/configs/plugin_TVMark.cfg
ginga/rv/plugins/Overlays.py
ginga/rv/plugins/TVMark.py
ginga/rv/plugins/TVMask.py

Fixes for Overlay, TVMark, and TVMask plugins

---

ginga/rv/Channel.py
ginga/rv/Control.py
ginga/rv/plugins/ChangeHistory.py
ginga/rv/plugins/Mosaic.py

This is a [fix for Ginga issue 602](https://github.com/ejeschke/ginga/issues/602).
It introduces a new API call for plugins to register change history messages when modifying images in place.
EDIT: Fix #602 , close #620

New change notification

---

ginga/rv/plugins/ChangeHistory.py
ginga/rv/plugins/Drawing.py

Drawing to use new notification for ChangeHistory

---

doc/rtd-pip-requirements

DOC: Fix RTD build

---

doc/manual/internals.rst

Address https://github.com/ejeschke/ginga/issues/637#issuecomment-372436610
Fix #638

DOC: Add new methods to custom WCS template

---

ginga/tests/test_wcs.py

This is a precursor for #327 . I need more tests so I would know GWCS works properly in Ginga-land.

Add more WCS tests

---

doc/install.rst

I did not make a comprehensive attempt at copy editing, but this one typo came to my notice.

One character typo

---

doc/manual/viewer.rst

Minor fixes that I was compelled to make while investigating #656 .
p.s. Not sure if new sections are needed, e.g., for `bokehw` and `jupyterw`, as I am not familiar with their development status.

DOC: Minor update to viewer.rst

---

ginga/BaseImage.py
ginga/canvas/types/astro.py

`Info` and `Crosshair` were crashing on me but they seem to work again with this patch.

Minor bug fixes so Info and Crosshair would work

---

ginga/web/README.md

DOC: Add readme for web folder 

---

ROADMAP.rst

DOC: Add Ginga roadmap

---

ginga/canvas/render.py

Fix writing out RGB as PNG with aggdraw

---

ginga/examples/configs/plugin_PixTable.cfg
ginga/rv/plugins/PixTable.py

This adds the following enhancements:
- add RMS to the summary statistics
- add standard move/draw/edit buttons for editing marks
- add a caption box to leave comments with marks
- add keystroke shortcuts to add, move or delete a mark

Enhancements for the PixTable plugin

---

ginga/qtw/Widgets.py

- possible fix for an issue sorting the TreeWidget in Qt backend
EDIT: Fix #257 
EDIT: Fix spacetelescope/stginga#83

Fix for github issue #257

---

.travis.yml
setup.py

Add python 3.7 to Travis tests, remove python 3.5

---

CODE_OF_CONDUCT.md
README.txt

DOC: Add code of conduct 

---

ginga/ImageView.py
ginga/rv/main.py
ginga/trcalc.py
ginga/util/io_rgb.py

Fix for upside-down RGB images

---

doc/WhatsNew.rst
ginga/examples/configs/plugin_MultiDim.cfg
ginga/rv/plugins/MultiDim.py

Fix #556 
Close #557 
cc @jdavies-st

ENH: Enable HDU sorting in MultiDim

---

ginga/conftest.py

This should fix the failure with astropy dev job. Please double check Travis CI results before merge.

TST: Fix import failure from astropy.tests

---

setup.py

MNT: Get rid of helpers deprecation warnings

---

ginga/examples/gw/clocks.py
ginga/gtk3w/GtkHelp.py
ginga/gtk3w/Widgets.py
ginga/qtw/Widgets.py
ginga/web/pgw/Widgets.py

- works correctly with editable=True now
- plus fixes for the clocks.py example program

Fix for gtk3 ComboBox

---

.travis.yml

Not sure why egg info job failed over at #787. Hopefully this will fix the failure if it is unrelated to the other PR.

Use xenial for Travis CI

---

ginga/util/iohelper.py

Recognize .fit as FITS

---

CITATION

Adds [this paper](http://www.aspbooks.org/a/volumes/article_details/?paper_id=39249) to CITATION.

Add recent ADASS paper to CITATION

---

ginga/__init__.py

Fixing an oversight from #814. My bad!

BUG: Fix version import and test runner

---

README.md
doc/install.rst
ginga/conftest.py

- updated README.md and install.rst
- also fixed an issue for running tests without `pytest-astropy-header` installed

Update documentation for building docs and running tests

---

setup.cfg

Install `sphinx_rtd_theme` when doing "pip install -e .[docs]"

Fix github issue #829

---

ginga/rv/plugins/Thumbs.py

Improves the efficiency of on-the-fly thumbnail generation for the `Thumbs` plugin.  Also fixes a bug where the proper thumbnail was not highlighted when a new image is opened in the viewer.
No new functionality or user options.

Enhance `Thumbs` plugin

---

ginga/ImageView.py
ginga/canvas/render.py
ginga/canvas/types/astro.py

- remove print statement
- change to correctly get set of images plotted
EDIT: Fix #855

Fix WCSAxes (fix #855)

---

doc/WhatsNew.rst
ginga/gtk3w/Widgets.py
ginga/qtw/Widgets.py

Fix Qt/PySide help crash

---

ginga/misc/Settings.py

- now allows line breaks in values, for more readable configs
- (fix #859)

Do more sophisticated parsing of config files

---

ginga/gtk3w/GtkHelp.py
ginga/gtk3w/Widgets.py
ginga/gw/Desktop.py
ginga/qtw/Widgets.py

This allows Ginga to remember the size and placement of the windows in workspaces that have been configured as MDI. If you close the reference viewer with some MDI windows opened and positioned, then start it again and open windows with the same names, they will be opened at the locations and sizes that they were when the program was closed.

Ginga will remember sizes and placement of windows in MDI workspaces

---

.github/workflows/ci_workflows.yml
ginga/tests/test_iqcalc.py

Given #880 might take some time yet, I will fix the CI here and then rebase over there.

Fix test failing due to missing scipy

---

.bandit.yaml
.github/workflows/ci_workflows.yml
ginga/doc/download_doc.py
ginga/gtk3w/GtkHelp.py
ginga/util/catalog.py
ginga/util/grc.py
ginga/util/heaptimer.py
ginga/util/iohelper.py
ginga/util/rgb_cms.py
ginga/util/videosink.py
ginga/web/jupyterw/JpHelp.py
ginga/web/pgw/PgHelp.py

Follow up of #872 . This uses [bandit](https://bandit.readthedocs.io/en/latest/) package to do simple security audit. If you think this is not necessary for Ginga, we can close without merge.

TST: Add security audit job

---

doc/ref_api.rst
ginga/colors.py
ginga/tests/test_colors.py
ginga/util/plots.py

Fix #883 . What do you think? Derived loosely from https://colorbrewer2.org/#type=diverging&scheme=RdBu&n=3
I don't think this needs a change log but let me know if you want one. Thanks.
**Updated plots**

Change FWHM plot colors, add to colors.py functionality

---

.readthedocs.yml
setup.cfg

DOC: Pin setuptools for RTD

---

.github/workflows/ci_workflows.yml
doc/WhatsNew.rst
ginga/tests/test_iqcalc.py
ginga/util/iqcalc.py
ginga/util/iqcalc_astropy.py
setup.cfg

Fix #895 
**TODO**
* Add/improve docstring
* Add test in `test_iqcalc.py`
* Implement alternative using photutils in `iqcalc_astropy.py` and make sure child test class runs it

Incorporate photutils into iqcalc_astropy and Pick

---

.github/workflows/ci_workflows.yml

TST: Fix broken dev deps job

---

.github/workflows/ci_workflows.yml

TST: Bump install-qt-action to v2.10.0 hash

---

ginga/doc/download_doc.py
ginga/util/toolbox.py

Compatibility with unreleased astropy 4.3 as a result of astropy/astropy#11006

MNT: Compat with astropy 4.3

---

.github/workflows/ci_workflows.yml

I noticed failure in old deps job that is supposedly fixed already upstream.

TST: Fix old deps job by bumping install-qt

---

.github/workflows/ci_workflows.yml

TST: Pin astropy in conda job

---

doc/WhatsNew.rst
ginga/examples/gw/example2.py
ginga/examples/gw/widgets.py
ginga/gtk3w/Widgets.py
ginga/qtw/Widgets.py
ginga/web/pgw/PgHelp.py
ginga/web/pgw/Widgets.py
ginga/web/pgw/js/ginga_pg.css
ginga/web/pgw/js/ginga_pg.js

* Some improvements to the pg widgets backend
* Widget improvements
- added set_value/get_value to ScrollBar
- added set_text/get_text to Button
- widgets sampler program updated to show changes
- fixed pgw Scrollbar rendering
- improvements to Label, TextEntry, TextArea, ComboBox, SpinBox, Slider
- updated widgets sampler program to show changes
- ComboBox allows scroll through entries with wheel now
- fixed bugs in ComboBox and TextArea
- implemented Frame set_widget() method
- implemented scroll_to_pct() method for ScrollArea
- improved GridBox
- implemented Stack and Frame Widgets
- improve GridBox functionality
- implement set_state for CheckBox and ToggleButton
- allow user to change increment value for SpinBox
Co-authored-by: Eric Jeschke <eric@naoj.org>

Improvements to pg web widgets 

---

ginga/util/wcsmod/wcs_astropy_ape14.py

Fix #960 . I don't understand why the "old way" works but not the APE 14 interface. I wonder if @mcara can advise here. The image is [jbt7a3k7q_flc.fits](https://stsci.box.com/s/gitjnk0xxb0q0g5hbygy7wtu7td5yhvd).
```
Filename: jbt7a3k7q_flc.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
0  PRIMARY       1 PrimaryHDU     281   ()      
1  SCI           1 ImageHDU       249   (4096, 2048)   float32   
2  ERR           1 ImageHDU        56   (4096, 2048)   float32   
3  DQ            1 ImageHDU        48   (4096, 2048)   int16   
4  SCI           2 ImageHDU       245   (4096, 2048)   float32   
5  ERR           2 ImageHDU        56   (4096, 2048)   float32   
6  DQ            2 ImageHDU        48   (4096, 2048)   int16   
7  HDRLET        1 NonstandardExtHDU     22 …
```

wcs_astropy_ape14: Fall back to old way when no convergence

---

doc/WhatsNew.rst
ginga/examples/pg/example2_pg.py
ginga/misc/Task.py
ginga/rv/main.py
ginga/web/pgw/Widgets.py
ginga/web/pgw/ipg.py

tornado has changed their event loop to use asyncio's native event loop; this necessitates a change in how we initialize ours

Fix creation of event loop in pg widgets backend

---

ginga/util/iqcalc.py

New scipy was released and has deprecation.

Fix scipy maximum_filter import deprecation

---

ginga/canvas/CanvasObject.py
ginga/canvas/DrawingMixin.py
ginga/canvas/types/image.py
ginga/canvas/types/layer.py
ginga/examples/gtk3/example1.py
ginga/examples/matplotlib/example1_mpl.py
ginga/examples/matplotlib/example2_mpl.py
ginga/examples/matplotlib/example3_mpl.py
ginga/examples/matplotlib/example4_mpl.py
ginga/examples/matplotlib/example5_mpl.py
ginga/examples/qt/example1_qt.py
ginga/examples/reference-viewer/MyLocalPlugin.py
ginga/examples/tk/example1_tk.py
ginga/examples/tk/example2_tk.py
ginga/mplw/ipg.py

- updates all example programs to avoid using the combination object
- will allow us to make #973 a smaller PR
- this doesn't actually deprecate anything

Prepare for removal of dual viewer/canvas object

---

doc/WhatsNew.rst
doc/install.rst
ginga/examples/matplotlib/example1_mpl.py
ginga/examples/matplotlib/example2_mpl.py
ginga/examples/matplotlib/example3_mpl.py
ginga/examples/matplotlib/example5_mpl.py
ginga/mplw/FigureCanvasQt.py
ginga/qtw/ImageViewQt.py
ginga/qtw/Plot.py
ginga/qtw/QtHelp.py
ginga/qtw/Widgets.py
ginga/toolkit.py
setup.cfg

This adds support for PyQt6 and PySide6 widget toolkits.  It removes support for PyQt4 and PySide, since those are not supported any more by `qtpy`.

Add support for PyQt6 and PySide6

---

.github/workflows/ci_workflows.yml
.github/workflows/open_actions.yml

Update GitHub Actions workflow versions, where applicable.

TST: Update workflow versions

---

doc/WhatsNew.rst
ginga/rv/plugins/Drawing.py
ginga/tests/test_ap_regions.py
ginga/util/ap_region.py

- adds "Sky" versions of the region support in ginga.util.ap_region
- adds 2 new buttons in Drawing plugin for importing and exporting regions
- updates for recent changes to the astropy-regions package
- updated plugin documentation

Add ability to import/export astropy-regions files in Drawing plugin

---

.readthedocs.yml

This is one way to fix #1020 albeit a little controversial, maybe.

DOC: Only build HTML on RTD

---

ginga/cmap.py

matplotlib deprecated mplDeprecation

MNT: Handle deprecated mplDeprecation

---

ginga/rv/plugins/Pipeline.py
ginga/util/action.py
ginga/util/pipeline.py
ginga/util/stages/base.py
ginga/util/stages/chmix.py
ginga/util/stages/crop.py
ginga/util/stages/cuts.py
ginga/util/stages/flipswap.py
ginga/util/stages/iccprof.py
ginga/util/stages/input.py
ginga/util/stages/output.py
ginga/util/stages/preview.py
ginga/util/stages/render.py
ginga/util/stages/rgbmap.py
ginga/util/stages/rotate.py
ginga/util/stages/scale.py
ginga/util/stages/sharpen.py
ginga/util/stages/whbal.py

- Add undo/redo capability to various stages
- Add stage docstrings
- Refinements to output stage, fixes for crop and rotate stages
- so crop and rotate stages can be inserted more than once
- Add load/save capability to all stages
- Misc updates to stages

Enhancements to the Pipeline plugin (not yet enabled by default)

---

.github/workflows/predeps_workflow.yml

Instead of one-off PRs, would save me time in the future to be able to just run a permanent workflow on demand.

TST: Workflow to test pre-releases

---

doc/WhatsNew.rst
ginga/modes/modeinfo.py
ginga/rv/main.py
ginga/util/compat.py

Fix a DeprecationWarning related to entry points in Python 3.11+

---

doc/WhatsNew.rst
ginga/util/evloop.py
ginga/web/jupyterw/JpHelp.py
ginga/web/pgw/PgHelp.py

Fix DeprecationWarning when getting tornado ioloop

---

doc/WhatsNew.rst
ginga/rv/Control.py
ginga/rv/main.py

- from channel viewer to a pop-up modal dialog
- shows version in title bar

Change implementation of splash ("About") dialog

---

.github/workflows/ci_workflows.yml
.github/workflows/predeps_workflow.yml

This hopefully will fix the nodejs warning that I see in Action log.

TST: Update jurplel/install-qt-action to v3.2.0

---

ROADMAP.rst
doc/FAQ.rst
doc/dev_manual/jupnotebooks.rst
doc/install.rst
ginga/examples/jupyter-notebook/Jupyter Widget Ideas.ipynb
ginga/examples/jupyter-notebook/ginga_ipython_demo.ipynb
ginga/util/wcsmod/wcs_kapteyn.py

Rename references to git branch 'master' to 'main'

---

.github/workflows/ci_workflows.yml
setup.cfg

- in advance of v5.0 release
- as discussed in #1053

Bump installation requirements for certain packages

---

.github/workflows/ci_workflows.yml
.github/workflows/predeps_workflow.yml
conftest.py
setup.cfg
tox.ini

Use tox for CI except for the conda job.
Fix #1054

TST: Use tox for CI

---

.github/workflows/ci_workflows.yml
tox.ini

TST: Use Python 3.12 with devdeps

---

ginga/util/grc.py

Temporarily address security update check

---

tox.ini

xref https://github.com/astropy/photutils/pull/1834
And also clean up devdeps setup.

TST: Use photutils nightly wheel, clean up devdeps

---

doc/FAQ.rst
doc/WhatsNew.rst
doc/dev_manual/viewer.rst
doc/install.rst
ginga/examples/gtk4/example1.py
ginga/examples/gtk4/example2.py
ginga/gtk4w/GtkHelp.py
ginga/gtk4w/ImageViewGtk.py
ginga/gtk4w/Plot.py
ginga/gtk4w/Viewers.py
ginga/gtk4w/Widgets.py
ginga/gtk4w/gtk_css
ginga/gw/GwHelp.py
ginga/gw/GwMain.py
ginga/gw/Plot.py
ginga/gw/PlotView.py
ginga/gw/PluginManager.py
ginga/gw/Viewers.py
ginga/gw/Widgets.py
ginga/rv/Control.py
ginga/rv/plugins/Info.py
ginga/toolkit.py
setup.cfg

Initial work to support GTK4 as an official backend
