ejeschke/ginga

doc/manual/plugins.rst
I believe "being overrided" should be "being overridden". I fixed two instances of this in the doc, under the "tips" section. The rest of the changes are just my Emacs automatically removing trailing whitespaces.
=> Fixed minor typo in plugins doc

ginga/Control.py
When I see traceback on `Errors` plugin, I want to know the type of exception associated with it. This adds the exception class name to the traceback shown.
The actual change is on Line 420. The rest is just my Emacs auto-removing trailing whitespace.
This was part of #101, but should be a PR in its own right.
=> Expose exception class name in Errors plugin

ginga/trcalc.py
This fixes #112, both the traceback and the `QPainter` warnings.
=> Fix for #112

ginga/util/io_rgb.py
There is no reason to print out stuff (i.e., the image dimension) to terminal when loading Ginga splash screen image when user clicks "About". Real change in on Line 317. The rest is just Emacs auto-removing trailing whitespace.
=> Suppress print statement on PPM load

ginga/qtw/plugins/Contents.py
* Fixed a bug where `Contents` `treeview` in Qt does not expand after being updated.
* Make `fileDict` use a consistent API to access `nameDict` (Qt only).
=> Contents treeview and nameDict access

ginga/misc/plugins/Pick.py
This fixes the warning below in `Pick` plugin:
```
.../matplotlib/cbook.py:137: MatplotlibDeprecationWarning: The "loc" positional argument to legend is deprecated. Please use the "loc" keyword instead.
warnings.warn(message, mplDeprecation, stacklevel=1)
```
=> Fix matplotlib deprecation warning in Pick

ginga/qtw/Widgets.py
Fixed a bug in the Qt Save dialog code where the extension is added to the file name even if the user has pressed 'Cancel' which creates hidden files instead of dropping the operation.
=> Add extension only if path is valid

ginga/BaseImage.py
I need a method to return a boolean mask of a given shape object that is the same size as the image. This cannot be achieved with `image.cutout_shape(shape_obj)` because that trims down to the bounding box of the shape.
Example usage of this new method:
```python
mask = image.get_shape_mask(shape_obj)
data = image.get_data()
data[mask] = my_fill_value
image.set_data(data)
```
=> Added method to compute full mask of a shape

ginga/Control.py, ginga/__init__.py, ginga/gtkw/__init__.py, ginga/gtkw/plugins/__init__.py, ginga/main.py, ginga/misc/__init__.py, ginga/misc/plugins/__init__.py, ginga/qtw/GingaQt.py, ginga/qtw/__init__.py, ginga/qtw/plugins/__init__.py
Turn `ginga.*.plugins` into namespace packages, as discussed in #92.
With this change, I can add my own custom plugins under the `ginga.qtw.plugins` namespace with this directory structure:
```
+- mygingastuff/
+- ginga/
|   +- __init__.py
|   +- qtw/
|   |   +- __init__.py
|   |   +- plugins/
|   |   |   +- MyGlobalPlugin2.py
|   |   |   +- MyLocalPlugin2.py
|   |   |   +- __init__.py
+- setup.py
```
The contents of each `__init__.py` (as pointed out by @embray):
```python
try:
__import__('pkg_resources').declare_namespace(__name__)
except ImportError:
pass
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```
This is an example `setup.py`:
```python
#! /usr/bin/env python
#
try:
from setuptools import setup
except ImportError:
from distutils.core import setup
setup( …
```
=> Turn ginga.*.plugins into namespace packages

ginga/Control.py, ginga/misc/plugins/Mosaic.py, ginga/misc/plugins/ThumbsBase.py
Fixed thumbs paths and missing `chinfo.readout` error messages.
1. For some reason, sometimes `chinfo` is returned as `None` and this causes an error in `Control.py`. Otherwise, does not seem to affect functionality.
2. Hardcoding thumbs directory to "/dev/null" in `Mosaic.py` is a bad idea. Changed it to working directory. Also, need to create nested directories if necessary.
3. There is a need to create nested directories if thumbnails are saved to `~/.ginga/thumbs` instead of local directory.
=> Fixed thumbs paths and missing chinfo.readout error messages

ginga/examples/configs/plugin_Thumbs.cfg, ginga/misc/plugins/ThumbsBase.py
This is a proposed solution for #184, as suggested by @hcferguson.
* Added `Thumbs` preferences to shorten labels for very long image names.
* Added image name to tooltip (not configurable).
* Added previously undocumented `thumb_length` setting to `config` example.
To enable shortening of thumbnail labels, add the following to `~/.ginga/plugin_Thumbs.cfg`:
```python
mouseover_name_key = 'NAME'
label_length = 25
#label_cutoff = 'front'
label_cutoff = 'back'
```
=> Thumbs preferences to hide labels

.travis.yml, doc/WhatsNew.rst, doc/api/index.rst, doc/api/main.rst, doc/api/wcsutil.rst, doc/conf.py, doc/index.rst, doc/manual/canvas.rst, doc/manual/developers.rst, doc/manual/index.rst, doc/manual/operation.rst, ginga/util/wcs.py, ginga/util/wcsmod.py
Fix warnings reported in #219 and more.
* Fixed doc warnings.
* Spiced up Sphinx `conf.py` a little.
* Added prototype of API doc (just to get `modindex` to work). *A lot* of work is needed to get all the API documented, but this shows the potential.
* Removed empty Search page (there is already a search box on top left menu).
* Cleaned up WCS in-code doc for API doc (no change to actual functionality).
* Added canvas doc that was previously (accidentally?) excluded in developer doc.
* My Emacs automatically removing trailing whitespace.
p.s: Also see #182
=> Fix/improve Ginga doc

ginga/qtw/QtHelp.py
This looks like a typo, and it caused all kinds of fun when trying to import the IPython qt console afterwards :)
=> Fix QT_API for PyQt5

ginga/qtw/Widgets.py
Qt `TreeView` should be sorted by the given leaf index, not "Column 1".
=> Qt TreeView to be sorted by leaf index

ginga/examples/configs/channel_Image.cfg, ginga/examples/configs/plugin_Contents.cfg, ginga/examples/configs/plugin_Thumbs.cfg, ginga/misc/plugins/Contents.py, ginga/misc/plugins/Thumbs.py
~~Qt~~ solution for `Contents` for #186.
~~If we want to be even more flexible, we can make the font color configurable, but will that be overkill?~~
* Enable user preference to set highlighted text color.
* Highlight active image properly when `highlight_tracks_keyboard_focus = True`. Highlighting logic is now like `Thumbs` (see https://github.com/ejeschke/ginga/compare/1c68ac3...1d6849d).
* Log failed highlighting as error instead of warning.
* Fixed error when image is removed from a channel, or when a channel is deleted.
* Also fixed similar error for `Thumbs` (follow up of #195).
* Added `sort_order` example in `channel_Image.cfg` (follow up of #226).
* Corrected verbiage in both `Contents` and `Thumbs` config examples.
* There is no need to make channel name all lowercase in the …
=> Highlight active image in Contents (Qt)

ginga/Control.py, ginga/main.py
* Fix banner not showing when `showBanner=True` in `general.cfg` (#229).
* Insert Ginga version info in banner header (#241).
=> Fixes for Ginga banner and version info display

ginga/misc/plugins/FBrowser.py, ginga/qtw/QtHelp.py
Implement multi-selection and wildcard/extension support for File menu in Qt (see #227). The Qt File menu had limited wildcard/ext support from #204 but it was lost in recent changes; I added that back in this PR. The menu should also be pretty flexible now, which allows user to do `shift+click`, `ctrl+click`, or enter things like `*.fits[2]` in the selection box. I am not aware of anything else that uses `FileSelection` class other than the file menu, but please let me know if this unintentionally breaks something else. As usual, I skipped the GTK portion; someone else can implement it if there is interest.
Also fixed error that occurs in `FBrowser` when directory and files are all selected at the same time (during multi-selection).
I toyed with the idea to also support comma-separated …
=> File menu (Qt) enhancement and FBrowser fix

ginga/util/wcsmod.py
This fixes up the `AstropyWCS2` class to actually function.  It looked like some of this was based on the prototype PR @Cadair wanted merged, which still isn't in Astropy, so that explains why it wasn't working.  But I've tested this PR and it seems to work with astropy 1.0 or 1.1, albiet in an "unsanctioned" way (setting `<frame>._data` directly).
cc @ejeschke 
Oh, and I believe this closes #181
=> Fix AstropyWCS2

doc/conf.py
Replaced `numpydoc` with Sphinx's `napoleon` extension, as suggested by @cdeil . Hopefully this would fix the RTD error reported by @ejeschke in #219.
=> Fix RTD erroring on numpydoc

ginga/util/io_fits.py
Get rid of PyFITS deprecation warning when Ginga saves a FITS file. You can reproduce it by using "Save" in the `Cuts` plugin.
=> Get rid of PyFITS deprecation warning

ginga/main.py, ginga/misc/plugins/Histogram.py
1. Fixed an error message when `Histogram` starts up (due to `self.histtag` set to `None`):
```python
2015-12-09 15:38:54,753 | E | Callback.py:89 (make_callback) | Traceback:
File ".../ginga-2.5.20151208223618-py2.7.egg/ginga/misc/Callback.py", line 72, in make_callback
res = method(*cb_args, **cb_kwdargs)
File ".../ginga-2.5.20151208223618-py2.7.egg/ginga/misc/plugins/Histogram.py", line 475, in cutset_ext_cb
self.redo()
File ".../ginga-2.5.20151208223618-py2.7.egg/ginga/misc/plugins/Histogram.py", line 246, in redo
obj = self.canvas.getObjectByTag(self.histtag)
File ".../ginga-2.5.20151208223618-py2.7.egg/ginga/canvas/CanvasMixin.py", line 92, in get_object_by_tag
obj = self.tags[tag]
```
2. Minor PEP8 fixes for `Histogram`.
3. Also put its `cut_levels()` error messages in log file.
4. …
=> Fixes for Histogram

ginga/misc/plugins/Cuts.py, ginga/misc/plugins/Histogram.py, ginga/misc/plugins/LineProfile.py
I have identified 4 plugins below with labels cut off, as mentioned in #246.
=> Tight layout for plots

ginga/qtw/Widgets.py
Make `QLabel` (Qt) text selectable. This is nice to have if user wants to copy the value from Ginga display.
=> Make QLabel (Qt) text selectable

ginga/colors.py, ginga/tests/test_colors.py
Made a few changes to the functions of the *ginga/colors.py* file
* lookup_color(): Added a meaningful error message if queried with a non-existent color name
* add_color(): Added a _validate_color_tuple() to validate the passed the color before adding it to color_dict
* remove_color():  Added a meaningful error message if a non-existent color name is tried to remove
* scan_rgbtxt(): Refactored this function into two; added a scan_rgbtxt_buf() which takes a string/buffer argument and parses it to read RGB values
**Tests**: Added tests for the old and the new functionalities of the file
=> Some modifications to the ginga/colors.py file and added tests for the same

ginga/misc/plugins/Header.py
Fix `Header` global plugin not updating properly on `'modified'` callback. I encountered this when I modify only the header of the image but not the data. I did something like this:
```python
hdr = image.get_header()
hdr[kwd] = val
image.make_callback('modified')
```
I noticed that the listing in `Header` did not update to reflect the new values until I click the sort checkbox.
=> Fix Header not updating on modified callback

ginga/Control.py
Fixed "changing highlight" error on `Contents` when loading multiple images and simultaneously also auto-loading another extension from those images, as reported in #260.
Thanks, @ejeschke ; Your suggestion works!
=> Fixed changing highlight error on Contents

ginga/examples/configs/plugin_Contents.cfg, ginga/misc/plugins/Contents.py, ginga/qtw/Widgets.py
Allow `Contents` global plugin to automatically resize columns to fit to its contents. Also fixed a bug in Qt version of `TreeView`.
This fixes #263.
=> Auto resize columns in Contents

ginga/examples/configs/plugin_ChangeHistory.cfg, ginga/main.py, ginga/misc/plugins/ChangeHistory.py
Added new `ChangeHistory` global plugin to log buffer change history. This PR makes the plugin available but not loaded by default. I am already using it in `stginga` but I thought it is general enough that Ginga will find it useful.
If you do not want this, just close this PR without merging. But if you want this, after the merge, I'll remove the copy from `stginga` and use this one instead.
**Here is some doc about the plugin (copied from its API doc):**
Keep track of buffer change history.
History should stay no matter what channel or image is active. New history can be added, but old history cannot be deleted, unless the image/channel itself is deleted.
The `redo()` method picks up a `'modified'` event and displays related metadata here. The metadata is obtained as follows:
```python …
```
=> New ChangeHistory global plugin

ginga/misc/Datasrc.py
Fixed `Datasrc` sorted keys not updated properly when an image is added to Ginga's data cache. This resulting in its `keys()` method returning empty list in some cases.
=> Fixed Datasrc sortedkeys not updated properly when image is added

ginga/misc/plugins/Mosaic.py
`Mosaic` now has useful description to go with `ChangeHistory` global plugin. Example:
```
timestamp1 -- Added image1
timestamp2 -- Added image2
```
=> Added meaningful change history for Mosaic

ginga/misc/plugins/MultiDim.py
This patch is a fix for the swap of NAXIS3 and NAXIS4 in the MultiLib window, as noted in #202. The code was inverting the indices, when no inversion was necessary. 
As noted in #202, the control buttons don't work with NAXIS4. Also the NAXIS4 GUI axis skips by two when dragging the pointer across the scale. These problems still persist; the only issue fixed is the axis swap.
=> Fix for swapped NAXIS3 and NAXIS4 in MultiDim [#202]

ginga/misc/plugins/PixTable.py
Prevent traceback when PixTable is started without any image. This fixes #306.
=> Prevent traceback when PixTable is started without any image

doc/manual/plugins_global/changehistory.rst, ginga/misc/plugins/ChangeHistory.py, ginga/util/toolbox.py
As discussed during sprint session. This automatically inserts config file contents from examples into plugins doc.
=> Enable auto insert of cfg into docstring

ginga/web/pgw/Widgets.py
In the web version of Widgets.py, we need to call the "do_operation" method and invoke the update_value/update_html operations to update the web page.
=> Call update_value/update_html in Label, ContainerBase, and Box widgets

ginga/cmap.py
I found a bug where matplotlib colormaps were not being loaded even if requested in Python 2.7. It is because the colormap names were compared to `str` when they are actually `unicode`.
While I am at it, I also made sure the hot new "viridis" colormap is present:
Also added some much needed docstrings.
=> Fix matplotlib colormaps not loading properly

ginga/cmap.py
Do not force loading Viridis colormap when it is not present (e.g., in Matplotlib v1.3 or earlier). The fix is to replace the colormap lookup with the correct dictionary that includes *all* the available colormaps. This is a follow-up of #319.
=> Do not force loading Viridis colormap when it is not present

ginga/misc/plugins/Drawing.py
In the `Drawing` local plugin, I added a "Create Mask" button to create boolean mask from drawn objects. The resultant mask has 1's where the drawn object contains the pixels, and 0's otherwise. Mask shape is taken from the displayed image when the button was pressed.
Not all drawn objects create mask that makes sense. For example, text or crosshair. But for the shapes that matter (e.g., circle, box, closed polygon, and the like), this should work properly.
The resultant mask will be inserted into Ginga as a new image, not unlike what happens when you use the `Mosaic` plugin.
=> Added mask creation functionality in Drawing

doc/FAQ.rst, ginga/doc/help.html, ginga/examples/ipython-notebook/ginga_ipython_demo.ipynb, ginga/util/wcsmod.py
This is a follow-up of 33c15be . Fixes #332.
* Replaced direct URL with `intersphinx` magic, where possible.
* Replaced remaining `readthedocs.org` with `readthedocs.io`.
p.s. I'd prefer to merge this *after* #313, as it is easier to resolve conflicts here than over there.
=> Doc links follow-up

ginga.desktop
This allows to use the desktop file to handle the file types that are actually specified by the mime tye.
=> Add file name to exec

ginga/misc/Task.py, setup.py
Set `use_2to3=False` in `setup.py`, as discussed in #338.
Thanks for investigating, @wtgee! Sorry for this oversight, @ejeschke !
=> Disable 2to3 in setup.py

ginga/LayerImage.py, ginga/cvw/CvHelp.py, ginga/misc/plugins/LineProfile.py, ginga/misc/plugins/MultiDim.py
There is no `xrange` anymore in Python 3, and the ranges are small enough
to just keep them as `range` in Python 2 as well. This closes #343.
=> Replace xrange() with range()

ginga/examples/gtk/example1_gtk.py
Removed an extra character in example1_gtk.py, file runs without error now.
=> Small typo fix in example file

ginga/examples/gtk/fits2pdf.py, ginga/misc/grc.py, ginga/util/fits2pdf.py, setup.cfg
Fixes #303. Also see #200.
For `grc`:
* Moved it to `misc` sub-package as `grc.py`.
* Renamed executable to `ggrc`, which is now an entry point.
* PEP8 fixes.
For `fits2pdf.py` (UPDATED):
* Moved it to `examples/gtk` sub-directory.
* Added a proper option parser.
* PEP8 fixes.
@ejeschke , please give this a spin and merge if satisfactory. c/c @olebole .
Examples (UPDATED):
```
$ which ggrc
~/anaconda/bin/ggrc
$ ggrc --help
Usage: ggrc [options] cmd [arg] ...
Options:
--version    show program's version number and exit
-h, --help   show this help message and exit
--debug      Enter the pdb debugger on main()
--host=HOST  Connect to server at HOST
--port=PORT  Connect to server at PORT
--profile    Run the profiler on main()
$ ggrc --version
2.5.20160603104100
```
=> Turn grc (now ggrc) and fits2pdf scripts into entry points

ginga/misc/ModuleManager.py
Currently, I see the following error with the dev version in Python 3:
```
2016-06-27 11:56:32,685 | E | ModuleManager.py:47 (loadModule) | Failed to load module 'FBrowser': name 'reload' is not defined
2016-06-27 11:56:32,685 | E | Control.py:384 (add_local_plugin) | Unable to load local plugin 'FBrowser': name 'reload' is not defined
```
This PR fixes the above in `ModuleManager.py`. I also added docstrings and addressed minor PEP8 issues.
=> ModuleManager cannot reload properly in Python 3

doc/conf.py
Fix `ImportError` in Python 3.5.2, as per astropy/package-template#180.
=> Fix ImportError in Python 3.5.2

ginga/misc/Task.py
@ejeschke This is a really small fix, I think it's in the correct place. The problem I was having was with blocking in the python terminal. I'm able to start up the HTML viewer and interact with no problems from a termina;, but when it comes time to exit python, the kernel was hanging and I had to kill it to get out. 
When I did some investigating the server thread was never being updated from 'start' to 'up', so when it came time to run stopall() it was just hanging.
I tested this with the notebook and a few consoles. See if this is the correct fix and works on your end?
=> Added thread up status to fix blocking in terminal

setup.py
Causing error with py 3.5.2, e.g https://travis-ci.org/astropy/conda-channel-astropy/jobs/141395583#L2108
=> Fixing configparser in setup

ginga/misc/plugins/SaveImage.py, ginga/util/toolbox.py
Fixed typo in `SaveImage` doc. Make `cfgpath` optional for `generate_cfg_example()`.
@ejeschke , nothing controversial here. I need `cfgpath` to be optional for one of my projects using that function.
=> Typo fix and adding optional keyword

ginga/canvas/types/astro.py, ginga/qtw/Widgets.py
When `util.wcsmod.AstropyWCS.radectopix` returns `nan` (caused by some kind of faulty FITS file), `Compass.draw` throws an error that causes the viewer at the top of the Info tab to stop working properly. I'm not sure what caused the error in `radectopix`, but the FITS files I'm using have some bizarre transformations on them from IRAF, so I guess the coordinates are all messed up. I set it to print `"BAD WCS"` like `Ruler` does when it can't resolve coordinates.
=> Fixed a bug in canvas.types.astro.Compass.draw

ginga/gw/Desktop.py, ginga/misc/Callback.py
Previously, when an error was thrown by a callback from an object without a `logger` attribute, the error remained silent. I set it to print errors to stderr when there is no available `Logger`, instead. That way, errors thrown from callbacks to objects without a `logger`, like `Button`, don't get suppressed.
In doing this, I discovered an error in gw/Desktop.py, where `Desktop` tries to log debug messages, but does not have a `logger`. I fixed that by assigning it a `logger` in its `__init__`.
=> Allowed errors to print out from callbacks without loggers

ginga/pilw/ImageViewPil.py, ginga/tkw/ImageViewTk.py
This fixes an issue where the PIL backend doesn't have the correct
surface size configured for the window and a render happens, causing
error messages for the first redraw.  Since the Tk backend frequently
relies on PIL to do the rendering, this fixes the Tk backend in those
cases.
-
=> Fix for PIL and Tk backend

ginga/gtkw/Widgets.py
Although it takes a dtype keyword parameter, the `gtk` `SpinBox` widget always returns `float` types. I added a `dtype` attribute to `SpinBox`, and a cast in `SpinBox.get_value` such that it will always return a value of the type that was specified at the object's creation. This makes the class more intuitive to use, and makes its behaviour more similar to `qtw.SpinBox`.
=> Fixed gtkw.SpinBox.get_value return type

.travis.yml, appveyor.yml
Unpin `qt=4` in Travis CI. Also update version numbers in Appveyor CI (not used).
This is an attempt to fix Travis CI failures regarding to `sip` version.
=> Unpin qt=4 in Travis CI

ginga/misc/plugins/ChangeHistory.py
Fixed `ChangeHistory` error message when drop-down row is selected. Minor `ChangeHistory` clean up.
Note: I can rebase this once #370 is merged, to avoid conflict with PEP8 clean-ups over there.
=> Fix ChangeHistory error message when drop-down row is selected

doc/manual/plugins_local/plottable.rst
Fixed `ref` tag syntax in `PlotTable` page. Ops, not sure how I missed that. I didn't notice it when I generated the page locally (but that was before #383).
=> Fix ref tag syntax in PlotTable page

ginga/util/io_fits.py
Fixes #398 
Fix circular import in `io_fits.py`. General PEP8 clean-up of `io_fits.py`.
=> Fix circular import in io_fits.py

ginga/misc/plugins/Cursor.py
Suppress the following traceback from `Cursor` when only table is displayed:
```
2016-11-22 13:33:14,929 | E | GwMain.py:86 (update_pending) | gui error: No data found
2016-11-22 13:33:15,030 | E | GwMain.py:90 (update_pending) | Traceback:
File ".../ginga-2.6.1.dev1266-py3.5.egg/ginga/gw/GwMain.py", line 81, in update_pending
res = future.thaw(suppress_exception=False)
File ".../ginga-2.6.1.dev1266-py3.5.egg/ginga/misc/Future.py", line 40, in thaw
res = self.method(*self.args, **self.kwdargs)
File ".../ginga-2.6.1.dev1266-py3.5.egg/ginga/misc/plugins/Cursor.py", line 109, in redo
self.readout_config(channel.fitsimage, image, readout)
File ".../ginga-2.6.1.dev1266-py3.5.egg/ginga/misc/plugins/Cursor.py", line 99, in readout_config
width, height = fitsimage.get_data_size()
File …
```
=> Suppress traceback from Cursor when only table is displayed

ginga/AstroImage.py
During the I/O refactoring in #397, somehow inherit primary header does not work properly anymore. This PR restores that behavior.
=> Restore inherit primary header functionality

ginga/qtw/Widgets.py
Replaced `setItemSelected(item,True)` with `item.setSelected(True)` in Qt widget. The former was deprecated in Qt4 and removed in Qt5. Fixes #412
=> Replaced obsolete setItemSelected

doc/manual/plugins_global/rc.rst, ginga/rv/plugins/RC.py, ginga/util/grc.py
Provides access to the Canvas of a given Channel within the RC plugin.
Includes a new canvas proxy within ginga.util.grc
Also added docs.  
Can add a Test if given guidance.  
I have confirmed it performs as intended in my own applications.
=> Add Canvas to RC

doc/manual/developers.rst, doc/manual/plugins_local/blink.rst, doc/manual/plugins_local/crosshair.rst, doc/manual/plugins_local/histogram.rst, doc/manual/plugins_local/overlays.rst
Resized screenshots and corrected typos in newly added doc.
Out of scope of this PR, but I think the screenshots should also include the image display area. For instance, it is more useful to see what the crosshair looks like in addition to the plugin UI. If you decide to do that, remember to increase the `:width:` value in the Sphinx image directive (800px should be sufficient).
p.s. Setting the width ensures that the screenshot does not appear too large. However, taking a smaller screenshot can also decrease the overall repo size.
=> Resized screenshots and corrected typos in doc

ginga/rv/Control.py, ginga/rv/plugins/Cuts.py
This PR adds support for converting docstrings to HTML on the fly so that the WBrowser plugin can display a more nicely formatted help text.  In this initial PR, only "Cuts" plugin is configured to show the help text in this way.
To use the plugin, the "docutils" package must be installed and the WBrowser plugin must be loaded.
=> Improve plugin help by providing on-the-fly HTML conversion

LICENSE.rst, LICENSE.txt, doc/LICENSE.rst, ginga/__init__.py, licenses/README.rst
Seems good practice to keep the license at the root of the repository.  This PR moves it back where it was originally.  Following cues from [this discussion](https://github.com/astropy/astropy/issues/5914).
This also updates a date to 2017.
We might want eventually to remove the duplicate `LICENSE.txt` file, but that name is referenced in many, many files.  For now I think it is ok to maintain two side-by-side files.
=> Updates to put license back in root of repository

doc/LICENSE.rst, doc/WhatsNew.rst, doc/manual/plugins_global/rc.rst, doc/manual/plugins_local/pick.rst
Currently, the subsections of `Pick` are also listed under "local plugins" listing. This PR fixes the subsections definitions.
=> Fix section definition of Pick documentation

ginga/rv/plugins/MultiDim.py
Fix #459 , follow up of a9943ebfb . @ejeschke , I think I fixed the behavior of switching active index when image is changed from another plugin (see https://github.com/ejeschke/ginga/issues/459#issuecomment-299299204 discussions). Also added `AstroTable` handling (there is a bit of lag there but we can figure out performance another time since it is not used by a lot of people) and minor PEP8 clean-ups.
The only thing I cannot figure out is how to move the slider to the actual slice being displayed when I switch away from a cube and switch back. Slider resets to 1 but the slice info (and slice image displayed) is the last active slice.
TODO:
=> MultiDim improvement

ginga/rv/plugins/Cuts.py, ginga/rv/plugins/Histogram.py, ginga/rv/plugins/LineProfile.py, ginga/rv/plugins/MultiDim.py, ginga/rv/plugins/Pick.py, ginga/rv/plugins/PlotTable.py, ginga/util/plots.py
Fix #486 -- Make `matplotlib` optional and make its import error more obvious. Tested this with and without `matplotlib`.
Fix #477 -- Handle `matplotlib` v2 deprecation warnings. Tested this with `matplotlib` 1.5.1 and 2.x.
=> Make matplotlib optional and handle v2 deprecation

ginga/rv/plugins/LineProfile.py, ginga/util/plots.py
Speed up `LineProfile` calculation by getting rid of Numpy masked array overhead. Fix #493.
I thought using masked array was a elegant solution but it is not feasible for large data cube. 😢 I probably over-designed it originally... Timing info available at https://gist.github.com/pllim/d0999e1c00d4ee45ccba2585c0b8146f .
Also fix #492.
c/c @bhilbert4 @aliciacanipe
=> Speed up LineProfile calculation etc

.gitignore, .travis.yml
Saw this in test log:
```
/home/travis/build/ejeschke/ginga/astropy_helpers/astropy_helpers/commands/build_sphinx.py:246:
AstropyDeprecationWarning: The "build_sphinx" command is now deprecated.
Use"build_docs" instead.
'"build_docs" instead.', AstropyDeprecationWarning)
```
Also added Python 3.6 to one of the tests and updated `.gitignore`.
=> Update Travis YML and gitignore

ginga/Bindings.py, ginga/ImageView.py, ginga/canvas/CanvasObject.py, ginga/canvas/CompoundMixin.py, ginga/canvas/DrawingMixin.py, ginga/canvas/coordmap.py, ginga/canvas/transform.py, ginga/canvas/types/astro.py, ginga/canvas/types/basic.py, ginga/canvas/types/image.py, ginga/canvas/types/mixins.py, ginga/canvas/types/utils.py, ginga/examples/gw/clocks.py, ginga/examples/qt/example2_qt.py, ginga/gw/Readout.py, ginga/mplw/CanvasRenderMpl.py, ginga/mplw/FigureCanvasQt.py, ginga/mplw/ImageViewMpl.py, ginga/mplw/transform.py, ginga/pilw/PilHelp.py, ginga/qtw/CanvasRenderQt.py, ginga/rv/plugins/Catalogs.py, ginga/rv/plugins/ColorMapPicker.py, ginga/rv/plugins/Drawing.py, ginga/rv/plugins/PixTable.py, ginga/trcalc.py, ginga/util/bezier.py, ginga/util/toolbox.py, ginga/util/wcsmod.py
This is a major refactoring of transforms and coordinate mapping for Ginga canvases.  The main goal of the refactoring is to allow numpy vectorization of coordinate transformations all the way up and down the chain for any graphics type.  This PR removes almost all uses of `map` and substitutes numpy arrays and vectorized transforms in many places.  The result is clearer and faster code.
The changes are to  (mostly) internal APIs, and there should be very little effect to users and developers. However, since this affects the rendering pipeline for all back ends, it should be tested quite thoroughly before merging.  One backend (matplotlib) is slightly broken by this PR and it needs a fix also before this can be merged.
- transform.py is vectorized, which changes the internal API
- files …
=> First step toward generalizing transforms to N dimensions

ginga/rv/plugins/SAMP.py, ginga/rv/plugins/SaveImage.py
This is needed as a result of astropy/astropy#6213 and astropy/astropy#6203. Otherwise, you will get deprecation warnings when Astropy 2.0 is released.
=> Ensure SAMP and FITS compatibility with Astropy 2.0

ginga/web/pgw/Widgets.py
Was trying to resize some widgets and found the set_length method wasn't working. The size was being hard coded to 20 and self.length wasn't being used, perhaps this is what it's supposed to be? Did some manual tests and the resize works when used like
```
catalog = Widgets.TextEntrySet()
catalog.set_length(5)
```
=> Allow text entry widgets to be resized

ginga/GingaPlugin.py, ginga/canvas/types/astro.py, ginga/examples/configs/plugin_Thumbs.cfg, ginga/rv/Channel.py, ginga/rv/Control.py, ginga/rv/plugins/Catalogs.py, ginga/rv/plugins/ChangeHistory.py, ginga/rv/plugins/Contents.py, ginga/rv/plugins/Header.py, ginga/rv/plugins/Mosaic.py, ginga/rv/plugins/Pan.py, ginga/rv/plugins/Thumbs.py
This adds Display/Move/Copy/Remove buttons to the bottom of the Contents UI.  Behavior of the Contents treeview is different.  First of all, selecting a file does not display it.  Secondly, multiple files can be selected, and using the standard Shift or Ctrl click the selection can be modified.  An action is selected by clicking one of the buttons at the bottom of the UI.  Move/Copy/Remove are all backed by pop-up dialogs to confirm the operation.
EDIT: Fix #107
=> Enhancement to Contents plugin to manage images in channels

setup.cfg, setup.py
Fix #540 by comparing how `setup(...)` is defined in Ginga and Astropy. I did not remove all metadata from `setup.cfg` but only changed what seem different, as I don't want to break things that already work. Wouldn't know if this fixes the PyPi metadata until next release.
xref #539
=> Clean-up setup script based on Astropy's

ginga/AutoCuts.py, ginga/rv/plugins/Pick.py, ginga/trcalc.py, ginga/util/contour.py
This introduces the capability to conveniently add contour plots on top of ginga canvases.  It requires a recent version of the `scikit-image` package.  If that is not available Pick falls back to using a matplotlib plot.
=> Update Pick plugin to have a more interactive contour plot

ginga/AstroImage.py
The `__init__` method uses the class attributes `ioClass` and `wcsClass` in the method definition for keyword defaults.  The class methods `set_ioClass` and `set_wcsClass` change their resepective class attributes, but the `__init__` method function call is not updated to reflect the change.  Solution: set the `__init__` keywords `ioclass` and `wcsclass` to `None`, test these for `None` first, then test `self.ioClass` and `self.wcsClass` before falling back on the defaults.
=> Make AstroImage respect set_ioClass and set_wcsClass methods.

ginga/rv/plugins/MultiDim.py
Without this fix, I get the following error in Python 3 when I click the "Save Slice" button in `MultiDim`:
```
Error making callback 'activated': write() argument must be str, not bytes
Traceback:
File ".../ginga/misc/Callback.py", line 128, in make_callback
res = method(*cb_args, **cb_kwdargs)
File ".../ginga/rv/plugins/MultiDim.py", line 169, in <lambda>
b.save_slice.add_callback('activated', lambda w: self.save_slice_cb())
File ".../ginga/rv/plugins/MultiDim.py", line 661, in save_slice_cb
cmap=plt.get_cmap('gray'), origin='lower')
File ".../matplotlib/pyplot.py", line 2319, in imsave
return _imsave(*args, **kwargs)
File ".../matplotlib/image.py", line 1347, in imsave
image.write_png(fname)
File ".../matplotlib/image.py", line 578, in write_png
_png.write_png(im, fname)
```
=> Open file in binary mode for MultiDim save slice

ginga/cmap.py
Fix #553.
Re-enable auto-loading of `matplotlib` colormaps. However, do not load deprecated colormaps. This is because loading deprecated ones result in duplicate colormaps (you have the deprecated one *and* the new one that is replacing it). Instead, you will see these messages on the terminal when you start Ginga:
```Error adding colormap 'spectral': The spectral and spectral_r colormap was deprecated in version 2.0. Use nipy_spectral and nipy_spectral_r instead.
Error adding colormap 'Vega10': The Vega10 colormap was deprecated in version 2.0. Use tab10 instead.
Error adding colormap 'Vega20': The Vega20 colormap was deprecated in version 2.0. Use tab20 instead.
Error adding colormap 'Vega20b': The Vega20b colormap was deprecated in version 2.0. Use tab20b instead.
Error adding …
```
=> Do not load deprecated Matplotlib colormaps

ginga/gtk3w/Widgets.py, ginga/rv/plugins/IRAF.py
The WebKit package is renamed as "WebKit2".  The correction fixes the gtk3 backend display.
=> Correct WebKit package name for gtk3

ginga/rv/main.py
Follow up of #609. I find the printed messages too noisy and there is nothing we can do about them.
=> Do not print out error when matplotlib colormap import fails

ginga/rv/plugins/Thumbs.py
This changes the canvas drawing logic for the Thumbs plugin so that it manages the thumbnails canvas much more efficiently, resulting in improved usability and responsiveness.  The main improvement is that it calculates which thumbnails should be visible based on the displayed area of the canvas and adds/removes thumbs as necessary to only show that set.
=> Efficiency improvement for Thumbs plugin

doc/WhatsNew.rst, doc/manual/operation.rst, doc/quickref.rst, ginga/Bindings.py, ginga/canvas/types/utils.py, ginga/examples/bindings/bindings.cfg.ds9, ginga/examples/bindings/bindings.cfg.standard, ginga/examples/bindings/bindings.cfg.trackpad, ginga/util/toolbox.py
This adds a special "meta" mode, which is an intermediate mode used to change modes.  In addition, the standard modes are all changed to be started from meta mode.  Under the new scheme, you press Space to invoke meta mode, then press the mode key that then invokes the mode you want.
The primary benefit of this modification is that it frees many key bindings that can be used for other things, and allows more keys to be bound within a mode.
The mode indicator has been updated to show a different color for the meta mode and also to show an indicator for all mode types, not just "locked" (L) and "softlock" (S), but also "held" (H) and "oneshot" (O).
This change affects the standard key bindings--documentation on quickref and manual has been updated.  The old behavior can be retained by …
=> Update mode change

doc/manual/customizing.rst
Single-backticks are used for API/ref linking, so I replaced `<pre>` kind of formatting with double-backticks. I only did it for `customizing.rst` as a follow-up of 490f3c5a265b7ae9ee75.
=> Fix Sphinx formatting in customizing.rst

ginga/util/toolbox.py
Fix #644 
I tested this fix with local doc build under both Ginga and `stginga`.
=> Avoid network access when examples not found

ginga/AstroImage.py, ginga/examples/configs/plugin_Header.cfg, ginga/rv/plugins/Header.py
This adds support for toggling on/off the mixing of the primary HDU header with the HDU header of the image being shown.
=> Add option to toggle on/off showing primary header in Header plugin

MANIFEST.in
As part of #644 investigation, I found that "experimental" folder is not distributed via PyPI tarball, so I am adding it here. ~~I think this will be useful as people who do `pip install` will still be able to use experimental plugins if they so choose.~~ (see below)
=> Add experimental to MANIFEST

doc/manual/customizing.rst
A user reported confusing documentation at http://ginga.readthedocs.io/en/latest/manual/customizing.html#adding-or-removing-plugins . Turns out what was actually needed was not clearly documented, so this PR adds the missing info to documentation.
c/c @rjavila
=> DOC: How to autostart plugins

ginga/examples/jupyter-notebook/MEF_slider_demo.ipynb
Add a new demo notebook on how to implement a simple slider for multi-extension FITS image.
A semi-rendered notebook can be viewed at https://gist.github.com/pllim/f0d465eaf4eb45f9bcd2cccd1779dea3 (except the widgets, which will only show properly when you run it locally).
=> DOC: Jupyter slider demo

ginga/ImageView.py
I got an error writing using `viewer.save_rgb_image_as_file("screenshot.png")` for `EnhancedCanvasView` under `jupyterw`. This patch fixed the error for me. I am not sure if this is specific to PIL or  not.
xref eteq/astrowidgets#1
=> Fix writing out to PNG with PIL

ginga/AstroImage.py, ginga/rv/plugins/Cuts.py, ginga/rv/plugins/LineProfile.py
This fixes an issue for the error message issued by numpy >= 1.15.0:
FutureWarning: Using a non-tuple sequence for multidimensional indexing is
deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this
will be interpreted as an array index, `arr[np.array(seq)]`, which will
result either in an error or a different result.
EDIT: Fix #677
=> Fix issue #677, for FutureWarning with numpy>=1.15.0

doc/ref_api.rst, ginga/AstroImage.py, ginga/tests/test_aimg.py, ginga/util/wcsmod/__init__.py, ginga/util/wcsmod/wcs_astropy.py
This PR adds convenience functions for working with astropy `NDData` objects.  Specifically, it adds support to the `AstroImage` class for loading `NDData` (or `NDData`-subclassed) objects and making an `NDData` object from an `AstroImage` object.  The conversions preserve data, header and wcs.
Examples:
```python
img = AstroImage()
img.load_nddata(ndd)
ndd2 = img.as_nddata()
ndd3 = img.astype('nddata')
```
this PR also adds support for converting to a `PrimaryHDU` object:
```python
hdu1 = img.as_hdu()
hdu2 = img.astype('hdu')
```
=> Add convenience functions for working with astropy NDData objects

ginga/ImageView.py, ginga/gtk3w/ImageViewGtk.py, ginga/gtkw/ImageViewGtk.py, ginga/qtw/ImageViewQt.py, ginga/rv/plugins/Blink.py, ginga/rv/plugins/Cursor.py
Fixes an issue where the Cursor plugin doesn't update its info when images are blinked in a channel, or the channels are blinked.  Fixes #683.
=> Fix Cursor plugin not updating info on image/channel blinking

ginga/Bindings.py, ginga/ImageView.py, ginga/RGBMap.py, ginga/canvas/types/utils.py, ginga/misc/Callback.py, ginga/misc/Settings.py, ginga/rv/Channel.py, ginga/rv/Control.py, ginga/rv/main.py, ginga/rv/plugins/Pick.py, ginga/rv/plugins/Preferences.py, ginga/rv/plugins/WCSMatch.py
This PR does two things: 1) refactors the way `RGBMap` objects manage their state, so that they can share the settings object of a ginga viewer widget; and 2) unifies the format of an "image profile" with a viewer `SettingGroup` object.  This simplifies the management of state between the viewer and the RGB mapper, but more importantly, opens up new possibilities for more advanced use cases for profiles.
Until now, profiles were only objects attached to the metadata of a `BaseImage`-subclassed object.  Using the Preferences (under the "Remember" category), certain state could be saved and restored to the viewer when moving between different images. Under this PR, basically almost all state from the viewer (meaning a channel image viewer in the context of a reference viewer) can be …
=> Profile support

ginga/table/AstroTable.py
This fixes the error message when displaying a table:
```
2018-08-27 12:16:50,628 | E | GwMain.py:76 (_execute_future) |
gui event loop error: get_header() got an unexpected
keyword argument 'include_primary_header'
2018-08-27 12:16:50,629 | E | GwMain.py:80 (_execute_future) | Traceback:
File ".../ginga/gw/GwMain.py", line 73, in _execute_future
future.thaw(suppress_exception=False)
File ".../ginga/misc/Future.py", line 46, in thaw
res = self.method(*self.args, **self.kwdargs)
File ".../ginga/rv/plugins/Header.py", line 225, in redo
self.set_header(info, image)
File ".../ginga/rv/plugins/Header.py", line 131, in set_header
header = image.get_header(include_primary_header=self.flg_prihdr)
```
=> Fix table header error msg

ginga/rv/Control.py, ginga/rv/plugins/RC.py, ginga/rv/plugins/WCSMatch.py
This adds two methods to the ginga shell that allow methods in a global or local plugin to be called.  This can be used e.g. from the RC interface, or internally.
=> Enable calling plugin methods from remote interface

setup.cfg
Probably an oversight when helpers changed the command from `build_sphinx` to `build_docs`.
=> Fix typo in setup.cfg 

ginga/tests/test_iqcalc.py, ginga/util/iqcalc.py
When using `Mosaic` plugin, I noticed this warning:
```
2018-11-07 16:04:20,707 | W | warnings.py:99 (_showwarnmsg) |
.../numpy/core/fromnumeric.py:688: UserWarning: Warning:
'partition' will ignore the 'mask' of the MaskedArray.
a.partition(kth, axis=axis, kind=kind, order=order)
```
Then, I found numpy/numpy#7330,  numpy/numpy#7345, and numpy/numpy#8669. To illustrate the problem using Numpy 1.15.4:
```python
>>> import numpy as np
>>> data_np = np.array([1, np.nan, 3, 4, 5])
>>> mdata = np.ma.masked_array(data_np, np.isnan(data_np))
>>> np.median(mdata)
.../numpy/core/fromnumeric.py:688: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
a.partition(kth, axis=axis, kind=kind, order=order)
.../numpy/lib/function_base.py:3250: RuntimeWarning: Invalid value …
```
=> Avoid using masked array for iqcalc

ah_bootstrap.py
This is an automated update of the astropy-helpers submodule to v3.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v3.1/CHANGES.rst). 
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!* 
Similarly to the core package, the v3.0+ releases of astropy-helpers require Python 3.5+. We will open automated update PRs with astropy-helpers v3.1.x only for packages that specifically opt in for it when they start supporting Python 3.5+ only. Please let @bsipocz or @astrofrog know or add your package …
=> Update astropy-helpers to v3.1

ginga/RGBImage.py, ginga/examples/bokeh/example1.py, ginga/examples/bokeh/example2.py, ginga/examples/gl/example2_qt.py, ginga/examples/gtk/example1_gtk.py, ginga/examples/gtk/example2_gtk.py, ginga/examples/gtk/fits2pdf.py, ginga/examples/gtk3/example1.py, ginga/examples/gtk3/example2.py, ginga/examples/gw/example2.py, ginga/examples/gw/shared_canvas.py, ginga/examples/matplotlib/example1_mpl.py, ginga/examples/matplotlib/example2_mpl.py, ginga/examples/matplotlib/example3_mpl.py, ginga/examples/matplotlib/example4_mpl.py, ginga/examples/matplotlib/example5_mpl.py, ginga/examples/pg/example2_pg.py, ginga/examples/qt/example1_qt.py, ginga/examples/qt/example2_qt.py, ginga/examples/tk/example1_tk.py, ginga/examples/tk/example2_tk.py, ginga/rv/Channel.py, ginga/rv/Control.py, ginga/rv/plugins/Mosaic.py, ginga/rv/plugins/MultiDim.py, ginga/util/io_fits.py, ginga/util/io_rgb.py, ginga/util/loader.py
This adds a "first-level" loader module to ginga.  This module allows opening a data item without knowing what it is first.  It works based off of the mime type of the file and also the magic function, if available.
This loader works with both the reference viewer as well as when using just the ginga widget.  This summarizes the difference:
Before:
```python
from ginga.AstroImage import AstroImage
image = AstroImage(logger)
image.load_file(some_path)
```
After:
```python
from ginga.util.loader import load_data
image = load_data(path, logger=logger)
```
Although it is shorter, the main reason it is better is that in the first instance we commit to creating a `AstroImage`, but if the file references an RGB file this is not necessarily the right type.  In the second case an `AstroImage`, a …
=> Enhance loader functionality

doc/WhatsNew.rst, doc/ref_api.rst, ginga/AstroImage.py, ginga/AutoCuts.py, ginga/canvas/types/astro.py, ginga/examples/qt/example_asdf.py, ginga/rv/Control.py, ginga/rv/plugins/MultiDim.py, ginga/tests/test_wcs.py, ginga/util/io_asdf.py, ginga/util/io_fits.py, ginga/util/iohelper.py, ginga/util/loader.py, ginga/util/wcsmod/__init__.py, ginga/util/wcsmod/wcs_astropy.py, ginga/util/wcsmod/wcs_astropy_ape14.py
This might still need unreleased ASDF and GWCS. It definitely requires Astropy 3.1 or later. But it does work, I propose that we merge this at its current state and improve it in future PRs, as needed. (Limited support is better than zero support?)
Fix #327
cc @hcferguson , @nden , and @drdavella
**TODO:**
**Open Questions:**
* `AstroImage.load_asdf()` -- How to let user specify where data and WCS are in ASDF?
* No way to load JWST data in a meaningful way without JWST data models hidden within JWST pipeline.
**Known issues (future PRs):**
* ~~`Compass` does not work.~~ 
* `WCSAxes` does not work. But this could be an issue with the test image rather than the plugin; need a better dataset to be sure.
* ~~Data cube not fully supported. `LineProfile` does not fully work.~~
* Very limited …
=> Implement basic interface to ASDF and GWCS

ginga/canvas/types/astro.py, ginga/util/wcsmod/wcs_astropy_ape14.py
Fix #729 . Turns out there was a bug in `wcspt_to_datapt` method in the `astropy_ape14` implementation from #719. 😅 
Also adds some logging to `WCSAxes` from the debugging process. No change log is needed as this is fixing something that is not released yet.
=> Fix wcspt_to_datapt bug for astropy_ape14

doc/WhatsNew.rst, ginga/rv/plugins/FBrowser.py, ginga/tests/test_iohelper.py, ginga/util/iohelper.py
Fix #727
This uses `pathlib`, which is new in Python 3.4. For Ginga 3.0, this is not a problem because its minimum supported Python is 3.5.
=> BUG: Fix FBrowser drag-and-drop on Windows

ginga/examples/configs/general.cfg
Follow up of #719. This adds `'astropy_ape14'` option to example of `general.cfg`. Thanks to @drdavella who brought this missing config to my attention.
=> Add astropy_ape14 to config example

doc/WhatsNew.rst, doc/conf.py, doc/install.rst, doc/rtd-pip-requirements, ginga/__init__.py, readthedocs.yml, setup.cfg, setup.py
Fix #663.
This supersedes #709.
@astrofrog , can you please have a look to see if I wrote the setuptools syntax correctly? Thanks! 🙏 
So, I think, with this change
```
python setup.py install
```
becomes
```
pip install .[recommended,qt5]
```
with the latter also `pip install` the specified dependencies.
If you are used to `python setup.py develop`, then it becomes
```
pip install -e .[...]
```
=> Consolidate pip dependencies between doc and setup

doc/WhatsNew.rst, ginga/rv/plugins/LineProfile.py
This was based on a feedback from JWST/MIRI instrument scientists when I did a demo for them. Using "Flux" as a default could be misleading.
=> Change LineProfile Y-axis label default

.travis.yml, ah_bootstrap.py
This is an automated update of the astropy-helpers submodule to v3.2.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 
Please note that since v3.2, ``sphinx-astropy`` needs to be explicitely listed as a dependency for building the documentation. 
A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v3.2.1/CHANGES.rst). 
We also wanted to let you know that we have made new releases of the astropy package-template. You can find the latest [cookiecutter template here](https://github.com/astropy/package-template) or if you prefer you can find a [rendered version of the template here](https://github.com/astropy/package-template/tree/master). 
*This is intended to be helpful, but if …
=> Update astropy-helpers to v3.2.1

ginga/examples/bokeh/example2.py, ginga/examples/gl/example2_qt.py, ginga/examples/gtk/example2_gtk.py, ginga/examples/gtk3/example2.py, ginga/examples/gw/example1_video.py, ginga/examples/gw/example2.py, ginga/examples/gw/shared_canvas.py, ginga/examples/matplotlib/example1_mpl.py, ginga/examples/matplotlib/example2_mpl.py, ginga/examples/matplotlib/example3_mpl.py, ginga/examples/pg/example2_pg.py, ginga/examples/qt/example2_qt.py, ginga/examples/qt/example_asdf.py, ginga/examples/tk/example2_tk.py, ginga/misc/grc.py, ginga/rv/main.py, ginga/util/mosaic.py, ginga/web/pgw/ipg.py
`optparse` will be deprecated in Python.  This changes uses to `argparse`, the heir apparent.
=> Change use of optparse to argparse

ginga/util/io_asdf.py, ginga/util/wcsmod/wcs_astropy_ape14.py
~Need to discuss how to best generalize the ASDF loading in reference viewer. This might change depending on how #764 goes (currently does not depend on it).~ Will just roll with this and follow up in a separate PR after #764 is rebased on this and merged.
These are the changes necessary for Python in Astronomy 2019 demo using Ginga standalone GUI (reference viewer) to view ASDF-in-FITS data file generated by JWST. Follow up of #719. Also see spacetelescope/stginga#155
cc @jdavies-st (in case you are interested), @hcferguson , and @eteq 
~Figure out why compass in `Pan` appears weird for the ASDF extension, but not FITS. Maybe spacetelescope/gwcs#241 ?~
**Future work:**
- Ginga should not emit error when RA or Dec is `NaN`, but instead silently format the string to something equivalent …
=> EXP: Support JWST ASDF-in-FITS in reference viewer

doc/FAQ.rst
It looks like the path changed at some point, but this should fix it I think
=> fix link to ds9 bindings

ginga/ColorDist.py, ginga/RGBMap.py, ginga/tests/test_colordist.py, ginga/trcalc.py, ginga/util/iqcalc.py
`numpy` changed the behavior of `clip()` in 1.17.0 where it returns a float when operating on an int array.  This PR provides workarounds for potential code sections that could be affected.
=> Protections against possible problems from numpy 1.17.0 clip()

ginga/ImageView.py, ginga/aggw/CanvasRenderAgg.py, ginga/aggw/ImageViewAgg.py, ginga/cairow/ImageViewCairo.py, ginga/cvw/CanvasRenderCv.py, ginga/cvw/ImageViewCv.py, ginga/gtk3w/ImageViewGtk.py, ginga/pilw/CanvasRenderPil.py, ginga/pilw/ImageViewPil.py, ginga/tkw/ImageViewTk.py, ginga/web/jupyterw/ImageViewJpw.py, ginga/web/pgw/ImageViewPg.py
This refactors the way viewers initialize their initial renderer. It allows for a flattening of the image viewer class hierarchy.  Some redundant code is removed.  Dynamic switching of the renderer in a live viewer is supported via the `choose_renderer` method.
The `cairo` renderer is made available to the Pg and Jupyter viewers, if the user has the `cairo` (`pycairo`?) package installed.  This renderer provides the most supported features (e.g. rotated text) and nicest text rendering for those viewers.
=> Refactor the way viewers initialize renderer 

doc/conf.py
Follow up of #798 . Not sure why we didn't see the RTD warning (which now causes failure for the PR check) back in #798. Maybe cache was not being cleared until after merge or something. 🤷‍♀ 
```
sphinx.errors.SphinxWarning: unknown mimetype for _static/astropy_logo.ico, ignoring
Warning, treated as error:
unknown mimetype for _static/astropy_logo.ico, ignoring
```
=> DOC: Fix ico mimetype warning

ginga/examples/bokeh/example2.py, ginga/examples/gl/example2_qt.py, ginga/examples/gtk3/example2.py, ginga/examples/gw/clocks.py, ginga/examples/gw/example1_video.py, ginga/examples/gw/example2.py, ginga/examples/gw/shared_canvas.py, ginga/examples/matplotlib/example1_mpl.py, ginga/examples/matplotlib/example2_mpl.py, ginga/examples/matplotlib/example3_mpl.py, ginga/examples/pg/example2_pg.py, ginga/examples/qt/example2_qt.py, ginga/examples/qt/example_asdf.py, ginga/examples/tk/example2_tk.py, ginga/misc/grc.py, ginga/rv/main.py, ginga/util/mosaic.py, ginga/web/pgw/ipg.py
this fixes a number of broken instances of ArgumentParser due to incorrect upgrade of the `usage` parameter.
=> Fixed broken instances of usage with ArgumentParser

.travis.yml
It is failing over at #787 and there is no good reason to keep it.
=> TST: Remove Numpy prerelease job

ginga/util/paths.py
This fixes an issue where if the user sets their GINGA_HOME environment variable then the home directory is not defined in ginga.util.paths
=> Fix an issue where home directory is not defined

doc/WhatsNew.rst, doc/dev_manual/canvas.rst, doc/ref_api.rst, ginga/canvas/types/astro.py, ginga/examples/gw/plot_ds9_regions.py, ginga/gw/sv.py, ginga/tests/test_ap_regions.py, ginga/util/ap_region.py
Provides a module (ginga.util.ap_region) that supports converting between astropy region objects and ginga canvas objects. 
Example program to show plotting the objects shown in the example "HorseHead" image for astropy regions.  See `ginga/examples/gw/plot_ds9_regions.py`.
=> Support astropy regions

ginga/canvas/types/astro.py, ginga/canvas/types/basic.py, ginga/canvas/types/image.py, ginga/canvas/types/utils.py
This adds alternative classes for many canvas types so that *all* types use an API where points are specified as single parameters.  This will be beneficial if we ever want to make a common change to coordinate handling across all canvas objects.
To illustrate, before:
```python
>>> canvas.add(Rectangle(x1, y1, x2, y2, ...))
```
after:
```python
>>> canvas.add(RectangleP(p1, p2, ...))
```
Subclasses are used to keep API compatible versions of the old class constructors available, and the new classes are not exposed as drawing catalog members yet (although you can explictly import them and use them. So there is no API change visible to any older code.
=> Unify the coordinate API for canvas types

setup.cfg
Oversight in #814 . My bad! This adds the `ginga` and `ggrc` CLI commands back.
=> BUG: Fix CLI entry points

doc/install.rst, setup.cfg
Looks like it is needed by `WBrowser` plugin.
=> Add docutils to dependency list

ginga/rv/plugins/PixTable.py
Fix for github issue #836.  Fixes a issue where if PixTable and Zoom are both launched on the same channel PixTable will report two sets of values in succession. The second set will in most cases not be correct.
This PR fixes this particular issue with PixTable, but it may be possible for a future plugin to suffer the same problem, so a more permanent fix should be implemented, preferably by refactoring how the `cursor-changed` callback is implemented.
EDIT: Fix #836
=> Fix for problem with PixTable plugin when used with Zoom

ginga/gw/Widgets.py, ginga/rv/plugins/MultiDim.py
Fixes the `get_oriented_box()` function to take an `aspect` parameter which can be used to force it to make more sane decisions about vertical or horizontal orientation.
EDIT: Fix #849
=> Make get_oriented_box() return more sane results

doc/WhatsNew.rst, ginga/canvas/DrawingMixin.py
- removes the cursor-changed callback from canvases. It only works correctly as coded when invoked from a viewer.
EDIT: Fix #848
=> Remove cursor-changed callback from canvases (fix #848)

ginga/canvas/types/astro.py
Alternative to #853.  Fixes the `super` calls to use the right subclass.
EDIT: Close #853
=> Fixed a bug where Annulus objects could not be moved

ginga/util/rgb_cms.py
I keep seeing this warning when I start Ginga but I don't think I need to do anything about it, so I think info would have been more appropriate.
```
2020-07-09 13:50:47,065 | W | rgb_cms.py:63 (profile_to_working_pil) | No working profile defined; leaving image unprofiled.
```
=> Downgrade rgb_cms warnings to info

ginga/rv/Control.py
I don't like the warning because even if I am okay with defaults (in the even of that file missing), I have to create the file to silence the warning. Therefore, I propose to downgrade it from warning to info. What do you think?
*Before* this patch:
```
2020-07-18 15:37:57,505 | W | Control.py:1429 (add_channel) |
no saved preferences found for channel 'Image':
Error opening settings file (/home/username/.ginga/channel_Image.cfg):
[Errno 2] No such file or directory: '/home/username/.ginga/channel_Image.cfg'
```
With this patch:
```
2020-07-18 15:59:25,384 | I | Control.py:1429 (add_channel) |
no saved preferences found for channel 'Image', using default:
Error opening settings file (/home/username/.ginga/channel_Image.cfg):
[Errno 2] No such file or directory: …
```
=> Downgrade channel_Image.cfg not found from warning to info

ginga/rv/main.py
Direct follow-up of #763 . With this, I now can do this without expanding `~` manually:
```
ginga --basedir=~/.ginga_twofer/
```
=> Expand user dir for basedir

ginga/gw/Desktop.py
Alternative to #865
EDIT: Close #865. Direct follow up of #763 .
=> Eliminate warning message when layout file does not exist

.gitignore
Not sure why but when `ginga` runs with the banner on, I get a residue `ginga/icons/.thumbs` directory in the source checkout.
=> Ignore icon thumbnail

doc/WhatsNew.rst, ginga/BaseImage.py, ginga/canvas/types/mixins.py, ginga/util/iqcalc.py, ginga/util/plots.py, ginga/util/vip.py
(Close #868)
Eliminates:
- VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
- Warning: 'partition' will ignore the 'mask' of the MaskedArray.
a.partition(kth, axis=axis, kind=kind, order=order)
=> Fix numpy deprecation warnings with numpy 1.19.0

ginga/canvas/CanvasObject.py, ginga/canvas/CompoundMixin.py, ginga/rv/plugins/Drawing.py, ginga/tests/test_canvas.py
Adds a `copy()` method to Ginga canvas objects.
This makes a shallow copy, which may not always work according to the intended purposes.  The `Drawing` plugin is modified to be able to use this to copy a selected object in edit mode.
In support of #874
=> Add copy() method to canvas objects

.github/workflows/ci_workflows.yml, ginga/util/wcsmod/common.py, ginga/util/wcsmod/wcs_astropy.py, ginga/util/wcsmod/wcs_astropy_ape14.py, setup.cfg
This deprecation warning started showing up and failing astropy-dev job:
```
E           astropy.utils.exceptions.AstropyDeprecationWarning: Transforming a frame instance to a frame class
(as opposed to another frame instance) will not be supported in the future.  Either explicitly instantiate the
target frame, or first convert the source frame instance to a `astropy.coordinates.SkyCoord` and
use its `transform_to()` method.
```
This is caused by astropy/astropy#10475 .
This PR proposes a fix for the astropy-dev job. It also clarifies that minimum version of `astropy` that we really support and added that to one of the jobs for testing.
=> MNT: Compatibility with astropy.coordinates

.github/workflows/ci_workflows.yml, doc/FAQ.rst, doc/WhatsNew.rst, doc/install.rst, ginga/misc/ModuleManager.py, setup.cfg
Fix #879 
Note: https://github.com/conda-forge/ginga-feedstock/blob/master/recipe/meta.yaml needs to be updated too at release time.
=> MNT: Drop Python 3.5 and 3.6

doc/WhatsNew.rst, ginga/util/plots.py
Fix #884 
Fixes an issue where a plot is not redrawn automatically when calling `clear()` on it.
=> Redraw plot after a clear operation

doc/WhatsNew.rst, ginga/gw/PlotView.py, ginga/rv/plugins/Cuts.py, ginga/rv/plugins/Pick.py, ginga/util/plots.py, setup.cfg
This removes support for matplotlib versions < 2.0. 
Since the "current" version of matplotlib seems to be 3.x I think this is reasonable.
=> Remove support for matplotlib < 2.0

.github/workflows/ci_workflows.yml, ginga/misc/tests/test_Callback.py
This PR makes pytest output more verbose, so we see exactly which test fails when failure happen. It also shows any screen output.
This PR also fixes the following screen output in the test log in the verbose mode set above (it currently does not fail the test but should be captured and tested anyway):
```
ginga/misc/tests/test_Callback.py::TestCallbacks::test_make_callback_raises_no_exception Error making callback 'test_name': test_callback_function() takes 0 positional arguments but 1 was given
Traceback:
File ".../ginga/misc/Callback.py", line 156, in _do_callbacks
res = method(*cb_args, **cb_kwargs)
PASSED
ginga/misc/tests/test_Callback.py::TestCallbacks::test_make_callback_raises_no_exception_completes_all_callbacks Error making callback 'test_name': test_callback_function() takes 0 …
```
=> TST: Verbose pytest and use capsys

ginga/cmap.py
Seems to work with matplotlib 2.1, so I don't think we need any version check.
Fix #890, fix spacetelescope/imexam#214 . Thanks to @jchavez1992 for reporting.
Caused by matplotlib/matplotlib#16991
=> MNT: Remove deprecated mpl usage

doc/WhatsNew.rst, doc/ref_api.rst, ginga/examples/configs/plugin_Pick.cfg, ginga/rv/plugins/Pick.py, ginga/tests/test_iqcalc.py, ginga/util/iqcalc.py, ginga/util/iqcalc_astropy.py, ginga/util/plots.py
This fixes #754 by implementing Lorentz fitting, but it is only available if `iqcalc_astropy` is used over `iqcalc`.
**TODO**
**Screenshot**
```python
import matplotlib.pyplot as plt
import numpy as np           
from ginga.util.iqcalc_astropy import IQCalc
arr1d = np.array([0., 9., 0., 0., 0., 34., 25., 60., 196., 602., 
1117., 1003., 413., 135., 29., 0., 3., 0., 4., 3.])
x = list(range(arr1d.size))
iqcalc = IQCalc() 
res_gaussian = iqcalc.calc_fwhm_gaussian(arr1d)
res_moffat = iqcalc.calc_fwhm_moffat(arr1d)
res_lorentz = iqcalc.calc_fwhm_lorentz(arr1d)
fit_gaussian = res_gaussian.fit_fn(x, res_gaussian.fit_args)
fit_moffat = res_moffat.fit_fn(x, res_moffat.fit_args)
fit_lorentz = res_lorentz.fit_fn(x, res_lorentz.fit_args)
fig = plt.figure()
ax1 = fig.add_subplot(311)
ax2 = …
```
=> New iqcalc_astropy module to use astropy to fit FWHM

doc/WhatsNew.rst, ginga/opengl/CanvasRenderGL.py, ginga/opengl/glsl/image.frag
Adds bicubic and bilinear interpolation methods to the OpenGL backend, which up till now only supported "nearest". No change to non-opengl backends, which already have these options.
=> Add bicubic and bilinear interpolation methods to OpenGL backend

setup.cfg
Fix #885 . Python 3.9 is already tested in CI as "3.x".
=> MNT: Add Python 3.9 to metadata

.github/labeler.yml, .github/workflows/open_actions.yml
This pull request adds auto PR labeler using https://github.com/actions/labeler in GitHub Actions. I tried to map some existing labels to associated files that seem obvious to me, but feel free to suggest changes if I got things wrong.
The motivation is to have more consistency in how the labels are applied to pull requests. Issues are not affected.
=> MNT: Add auto PR labeler

doc/WhatsNew.rst, ginga/rv/plugins/Pick.py
The Pick plugin is supposed to autozoom the pick and contour images in the plugin GUI, at least until the user overrides the zoom level.  This change makes it work correctly.
=> Fixed Pick plugin to autozoom the pick and contour images

ginga/gtk3w/GtkHelp.py, ginga/gtk3w/Widgets.py, ginga/qtw/Widgets.py, ginga/web/pgw/Widgets.py
Fixes some event handling for the Gtk version of Splitter widget and also provides a way to specify a size for the divider (splitter handle) image.
=> Fixes for Gtk Splitter widget

ginga/Bindings.py, ginga/ColorDist.py, ginga/canvas/CanvasObject.py, ginga/canvas/transform.py, ginga/canvas/types/astro.py, ginga/canvas/types/basic.py, ginga/canvas/types/image.py, ginga/canvas/types/mixins.py, ginga/cmap.py, ginga/rv/plugins/RC.py, ginga/tests/test_colordist.py, ginga/tests/test_trcalc.py, ginga/trcalc.py, ginga/util/iqcalc.py, ginga/util/vip.py, ginga/util/zscale.py
Numpy 1.20 is released and is causing warnings like this in Ginga:
```
E   DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`.
To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe.
If you specifically wanted the numpy scalar type, use `np.float64` here.
E   Deprecated in NumPy 1.20; for more details and guidance:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
```
E DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`.
To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe.
When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision.
If you wish to review your current use, check the release note …
```
=> MNT: Use float instead of np.float, int instead of np.int

doc/WhatsNew.rst, ginga/gw/Widgets.py, ginga/rv/plugins/Blink.py, ginga/rv/plugins/ChangeHistory.py, ginga/rv/plugins/Collage.py, ginga/rv/plugins/Crosshair.py, ginga/rv/plugins/Drawing.py, ginga/rv/plugins/Histogram.py, ginga/rv/plugins/LineProfile.py, ginga/rv/plugins/Mosaic.py, ginga/rv/plugins/MultiDim.py, ginga/rv/plugins/Overlays.py, ginga/rv/plugins/Pick.py, ginga/rv/plugins/PixTable.py, ginga/rv/plugins/PlotTable.py, ginga/rv/plugins/Preferences.py, ginga/rv/plugins/Ruler.py, ginga/rv/plugins/SaveImage.py, ginga/rv/plugins/TVMark.py, ginga/rv/plugins/TVMask.py, ginga/rv/plugins/Toolbar.py, ginga/rv/plugins/WCSAxes.py, ginga/rv/plugins/WCSMatch.py, ginga/rv/plugins/Zoom.py
Adds an "orientation" setting to all plugins that use the "get_oriented_box" function.  It allows the user to fix (override) the auto-orientation.
=> Add orientation setting to all plugins that are orientable

.github/workflows/ci_workflows.yml
Numpy and Scipy have builds in Python 3.9 now.
=> TST: Use latest Python for dev tests

setup.cfg
I was wondering how #930 fell through the cracks and then I noticed that we have been ignoring warnings in `pytest`.
~I suspect this will smoke out a lot of warnings, so I still put this on draft status for now until we can figure out how to handle them.~
Well, that was easier than expected. This is ready for review now.
=> TST: Stop ignoring warnings

doc/install.rst, ginga/AstroImage.py, ginga/aggw/CanvasRenderAgg.py, ginga/pilw/CanvasRenderPil.py, ginga/pilw/PilHelp.py, setup.cfg
I see this warning while working on astropy/astrowidgets#125
```
.../ginga/aggw/CanvasRenderAgg.py:215: DeprecationWarning: The binary mode of fromstring is deprecated,
as it behaves surprisingly on unicode inputs. Use frombuffer instead
arr8 = np.fromstring(self.surface.tobytes(), dtype=np.uint8)
```
=> MNT: Replace fromstring with frombuffer, bump numpy minversion

ginga/tests/test_aimg.py
Ignore WCS warning from astropy 4.3.dev, possibly caused by WCSLIB 7.4 upgrade (astropy/astropy#11260).
This fixes the dev job failure in CI.
=> TST: Ignore WCS warning from astropy 4.3.dev

ginga/_astropy_init.py
This is probably leftover from package template. Ginga does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497
=> MNT: Remove unused astropy config code

doc/WhatsNew.rst, ginga/Bindings.py, ginga/examples/configs/plugin_Histogram.cfg, ginga/rv/plugins/Histogram.py, ginga/util/plots.py
Fix #942
You can set cut levels by clicking in the histogram plot:
* left click: set low cut
* middle click: reset (auto cut levels)
* right click: set high cut
In addition, you can dynamically adjust the gap between low and high cuts by scrolling the wheel in the plot (i.e. the "width" of the histogram plot curve).  This has the effect of increasing or decreasing the contrast within the image.  The amount that is changed for each wheel click is set by the plugin configuration file setting ``scroll_pct``.  The default is 10%.
=> Add interactive setting of cut levels within Histogram plugin

ginga/tests/test_aimg.py
Revert #938 as the `datfix` warning should no longer be issued because `astropy` updated bundled `wcslib`.
Also see astropy/astropy#11549
=> MNT: Un-ignore datfix warning from astropy 4.3.dev

doc/install.rst, doc/optimizing.rst, ginga/examples/configs/general.cfg, ginga/examples/gtk3/example2.py, ginga/examples/gw/example1_video.py, ginga/examples/pg/example2_pg.py, ginga/examples/qt/example2_qt.py, ginga/examples/qt/example_asdf.py, ginga/rv/main.py, ginga/trcalc.py, ginga/web/pgw/ipg.py
Previously, OpenCv support had to be explicitly enabled via a command line switch or option in a configuration file.  This was due to a problem importing `cv2` that could crash the application on some platforms.  The `OpenCv` project has fixed that bug some time ago and for quite a while now, Ginga has been quietly enabling OpenCv support by default.
This PR removes the `--opencv` switch from example programs and updates the documentation to indicate that it is used by default if installed.  The option is retained on the reference viewer, however it will generate a logger warning that the option has been deprecated.
=> Clarify that opencv acceleration is used by default

.github/workflows/ci_workflows.yml
Fix #961 and hopefully error like this in a future release:
```
! [rejected]          v3.2.0     -> v3.2.0  (would clobber existing tag)
```
=> TST: Update CI workflow

doc/install.rst, doc/optimizing.rst, ginga/trcalc.py
This removes the use of the `numexpr` package for optimizing rotations.  There are several other (better)  ways to optimize rotations including using `opencv` and `pyopengl` packages, which also add other optimizations.
=> Remove numexpr optimizations

ginga/rv/plugins/Pick.py, ginga/util/iqcalc.py, ginga/util/plots.py
Changes the center point of FWHM calculation in `evaluate_peaks` from the local peak to the center-of-mass centroid of the local peak, if it can be calculated.
This may result in a slightly more accurate FWHM in the `evaluate_peaks` pass that can be used to solve the problem outlined in #969
Fix #969
=> Change Pick plot of FWHM to match rest of UI report

ginga/rv/plugins/Contents.py, ginga/rv/plugins/Thumbs.py
This makes the `Contents` plugin in the reference viewer behave so that if the `genthumb` setting in the channel is set to False that
no entry is made in Contents. Additionally, if an individual image has `nothumb`  == True then no entry is added.
This makes Contents behave similarly to Thumbs for channel and image settings.
=> Change Contents so that "genthumb" setting of channel applies

ginga/aggw/CanvasRenderAgg.py, ginga/cairow/CanvasRenderCairo.py, ginga/cvw/CanvasRenderCv.py, ginga/mockw/CanvasRenderMock.py, ginga/mplw/CanvasRenderMpl.py, ginga/opengl/CanvasRenderGL.py, ginga/pilw/CanvasRenderPil.py, ginga/qtw/CanvasRenderQt.py
This was supposed to be the default renderer in release 3.2 but got reverted to some odd rendering that I noticed on one or two occasions.  This restores it to the default.  Need to confirm that it is working properly.
=> Restore the pipeline renderer as the default renderer

ginga/util/wcsmod/wcs_astropy.py
Fixes the routines ``radectopix`` and ``wcspt_to_datapt`` in the WCS wrapper for astropy so that if the convergence fails it falls back to the best solution (based on the information in [this issue](https://github.com/astropy/astropy/issues/3203)).
The rationale for this is that these routines are mainly used for routines like drawing a compass, etc and do not need extreme accuracy of solution.
=> Add NoConvergence workaround for radectopix in wcs_astropy.py

setup.cfg
While newer stable releases upstream have fixed this problem, the `astropy` pulled by `older_deps` job does not have this fix because `astropy` itself dropped support for Python 3.7. So, we still need to ignore this warning.
Fix #980
=> TST: Ignore older_deps deprecation warning

doc/WhatsNew.rst, doc/ref_api.rst, ginga/AutoCuts.py, ginga/Bindings.py, ginga/ImageView.py
This PR updates the auto cuts algorithms in the following ways:
- auto cuts features in the viewer can now work properly with images plotted on the canvas (not just a single loaded image); for example, the output of the `Collage` plugin
- the auto cuts algorithms that defaulted to taking a small crop sample from the center of the image ('histogram' and 'stddev') are expanded to include an option to sample the data in a grid pattern across the image. This is useful for large images (collages or large data frames such as mosaics), where a small crop from the center is not representative of the data across the image and the image is much too large to apply the algorithm to the full data.
- adds a `full_px_limit` parameter to 'histogram' and 'stddev' that specifies the number of pixels limit …
=> Update autocuts algorithms 

doc/WhatsNew.rst, ginga/AstroImage.py, ginga/BaseImage.py, ginga/rv/Control.py, ginga/rv/plugins/Header.py, ginga/table/AstroTable.py, ginga/table/TableView.py, ginga/util/io_fits.py
This PR refactors AstroImage, AstroTable and ginga.util.io_fits in the following ways:
- the primary header is saved as a metadata item called 'primary_header' (the header is already saved similarly as 'header'); this makes the handling of these two entities similar.
- the astropy/fitsio specific details for loading an HDU has been moved from AstroImage and AstroTable to ginga.util.io_fits. This encapsulates the details of the specific support package in io_fits
- added loading of FITS tables via the `fitsio` package in io_fits
- modified the TableView class to be able to view tables loaded with either astropy or fitsio
=> Refactor handling of inherit_primary_header in AstroImage

doc/WhatsNew.rst, ginga/AstroImage.py
This begins the removal of the `save_primary_header` and `inherit_primary_header` attributes and kwargs from AstroImage.
The saving of the primary header is done when loading an image through the `io_fits` module and it is merged when `include_primary_header==True` in the `AstroImage` `get_header`() method.
The two kwargs issue a deprecation warning if used when creating an AstroImage.
=> Remove save_primary_header, inherit_primary_header attributes

doc/install.rst, ginga/canvas/render.py, ginga/rv/plugins/Compose.py, ginga/tkw/ImageViewTk.py, ginga/trcalc.py, ginga/util/io_rgb.py, ginga/util/loader.py, ginga/util/rgb_cms.py, ginga/util/stages/output.py, setup.cfg
Since we are planning to deprecate the mock backend, and `pillow` is used in many places, as well as being a very common package, this adds `pillow` as a requirement.  It also changes the optional `piexif` package to `exifread`, which is a little less code verbose to use, a bit more popular and well maintained.
This also restores a couple of lines needed in the OpenCv RGB file handler to make auto-orientation of RGB images work correctly.
=> Make pillow a required package, change piexif to exifread

ginga/rv/plugins/SaveImage.py, ginga/tests/test_wcs.py, ginga/trcalc.py, ginga/util/rgb_cms.py, ginga/util/toolbox.py
This pull request is to get rid of these warnings in CI that appeared with Pillow 9.1.0 release:
`DeprecationWarning: XXX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.XXX instead.`
` DeprecationWarning: XXX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Intent.XXX instead.`
=> MNT: Replace deprecated PIL calls

.readthedocs.yml
RTD has changed their way to specify Python version. We are using the same thing in `astropy`, so should be uncontroversial.
=> DOC: Update RTD env

doc/WhatsNew.rst, ginga/examples/configs/general.cfg, ginga/rv/main.py, ginga/util/io_fits.py
This PR adds an option to suppress FITS verification warnings when using `astropy.io.fits` as the FITS file opener.
It is opt-in, and can be invoked by adding `--suppress-fits-warnings` to the command line, or by adding `suppress_fits_warnings = True` to the `general.cfg` configuration file in the user's `$HOME/.ginga` folder.
- fix #997
=> Add option to suppress FITS verify warnings from astropy.io.fits

doc/WhatsNew.rst, ginga/Bindings.py, ginga/ImageView.py, ginga/canvas/CanvasObject.py, ginga/examples/gw/widgets.py, ginga/gw/GwMain.py, ginga/misc/Bunch.py, ginga/rv/Control.py, ginga/rv/plugins/Cuts.py
Fixed a longstanding issue where events registered on a canvas could be masked by default key/cursor bindings (not associated with a mode). This meant, for example, that only certain keystrokes could be captured by an event handler registered on a ginga canvas, because any keystrokes that had a default binding would take precedence. Now such bindings are only executed if the event is not handled by any active canvas bindings.
=> Fixed a longstanding issue for event handling on a ginga canvas

doc/WhatsNew.rst, ginga/examples/configs/plugin_Pick.cfg, ginga/rv/plugins/Pick.py
This removes two confusing checkbox options from the Pick plugin.
The "quick" mode is not actually quicker for most use cases and just makes the plugin more complex and confusing to users.
=> Simplify the Pick plugin

doc/WhatsNew.rst, ginga/AstroImage.py, ginga/AutoCuts.py, ginga/ImageView.py, ginga/Mixins.py, ginga/canvas/CanvasMixin.py, ginga/canvas/CanvasObject.py, ginga/canvas/CompoundMixin.py, ginga/canvas/DrawingMixin.py, ginga/canvas/coordmap.py, ginga/gw/PluginManager.py, ginga/misc/CanvasTypes.py, ginga/misc/ModuleManager.py, ginga/misc/Settings.py, ginga/rv/Control.py, ginga/rv/main.py, ginga/table/TableView.py, ginga/util/catalog.py, ginga/util/io_fits.py, ginga/util/iqcalc.py, ginga/util/wcs.py, ginga/web/pgw/ipg.py
This removes a number of camel-case deprecated methods.  It is targeted for release 4.0.
There are a few other deprecated items also removed.
supercedes #990
fix #898
=> Remove camel-case deprecated calls

ginga/util/wcs.py
This is a follow-up of #996 . There are duplicates in the `__all__` import namespace.
=> Remove duplicate namespace imports in __all__

ginga/rv/plugins/TVMark.py
Changes ``contains_arr()`` to a call to ``contains_pts()``.
=> Change deprecated call to contains_arr()

doc/WhatsNew.rst, ginga/RGBMap.py, ginga/examples/gw/example1_video.py, ginga/util/stages/render.py, ginga/util/stages/rgbmap.py
Refactors the `ginga.RGBMap.RGBMap` object to use a pipeline implementation.
This simplifies the understanding and maintenance of the coloring algorithm (in a similar manner to the way the standard renderer was refactored to use a pipeline).
Backward compatibility with the previous RGBMap class is largely preserved.
=> Refactor rgbmap to use a pipeline

.github/workflows/ci_workflows.yml
Fix #1048 
Not sure why conda is pulling astropy 5.1 when astropy 5.2.2 is already available on conda-forge. Maybe forcing a pin update would do it?
=> TST: Update pin on conda job

ginga/pilw/PilHelp.py
=> Fix for change in API in PIL v10.0

ginga/rv/Control.py, ginga/rv/main.py
This adds some additional options to the ReferenceViewer class initializer in ginga.rv.main so that the startup channels, application name, and application home directory can be more easily customized. The defaults are all maintained as before.
=> Increase configurability of ReferenceViewer start up

doc/WhatsNew.rst, ginga/rv/plugins/Catalogs.py, ginga/util/catalog.py
Dear Dr. Jeschke,
I have added support for vizier catalogs, with APASS DR9 as the default catalog source.
It includes:
- the possibility to do a box query limited to the image, hence no need to use the "limit stars to area" option and no obsolete data returned in the query
- the possibility to return only specific catalog columns of interest
- vizier catalogs can have NaN values for magnitudes, for these only a point is plotted and no circle. NaN values are not taken into account for the color coding range.
Would be great if you could merge this feature.
Thanks,
Eric Broens
=> Feature vizier catalogs

doc/WhatsNew.rst, ginga/examples/configs/general.cfg, ginga/gtk3w/Widgets.py, ginga/qtw/Widgets.py, ginga/rv/Control.py, ginga/web/pgw/Widgets.py
- pops up a confirmation dialog that confirms you intend to quit
- adds support across backends
- can be overridden by adding a line to your general.cfg
- example general.cfg updated
=> Add a confirmation dialog when the reference viewer is closed

ginga/util/catalog.py
Move the Vizier row limit setting to inside the import try..except to avoid an error if `astroquery` is not imported.
=> Only set Vizier row limit if imported

setup.cfg
I didn't know you have a release branch. Should have backported this. Your v4.1.1 doc did not build.
=> Fix RTD build in v4.1.x

setup.cfg, tox.ini
Fix devdeps job that is failing.
xref https://github.com/astropy/astropy/issues/15638
=> TST: Fix devdeps

.github/dependabot.yml
There is no need to run CI here and you won't see the benefit until after merge. This would allow Dependabot to submit PRs to upgrade things like GitHub Actions versions as needed.
See https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide
=> Unleash dependabot

doc/WhatsNew.rst, ginga/opengl/CanvasRenderGL.py, ginga/rv/plugins/MultiDim.py, setup.cfg
- fix #1095
for rationale, [see this](https://docs.python.org/3.10/whatsnew/3.10.html#distutils-deprecated)
This will be applied also to the 5.0.1 release.
=> Remove imports of distutils

ginga/util/wcs.py
Compass N-E to be more robust by using small angular offsets when determining compass properties.
This is from https://github.com/spacetelescope/jdaviz/pull/2867 by @astrofrog on the same piece of algorithm we borrowed from Ginga (https://github.com/spacetelescope/jdaviz/blob/main/licenses/GINGA_LICENSE.txt).
=> ENH: Compass N-E to be more robust

ginga/tests/test_iqcalc.py
Adjust Lorentz1D FWHM result to be compatible with astropy v7.0 probably due to astropy/astropy#16794 bug fix upstream. Without this patch, the devdeps job fails. Example failure log: https://github.com/ejeschke/ginga/actions/runs/10448173088/job/28928224243
Would be nice if @larrybradley can confirm that such a change downstream is actually expected from the Lorentz1D `fit_deriv` fix. 🙏
=> TST: Adjust Lorentz1D FWHM result for devdeps

ginga/tests/test_iqcalc.py
The patch was backported and is now in Astropy ~~6.3.1~~ 6.1.3, which should be the minversion. That is a trivial fix to https://github.com/ejeschke/ginga/pull/1106#discussion_r1739880234.
=> TST: Fix Astropy minversion for Lorentz1D result change

.github/workflows/ci_workflows.yml, .github/workflows/open_actions.yml, .github/workflows/predeps_workflow.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
=> MNT: Use hash for Action workflow versions and update if needed

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
This pull request adds templates for new issues and pull requests. For issues, they are separated into feature request, bug report, and question categories. Also see https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests
=> MNT: Add issue and PR templates
